import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

test('input panel exposes one scan start button only', () => {
  const source = fs.readFileSync('src/components/InputPanel.jsx', 'utf8')
  assert.equal((source.match(/type="submit"/g) || []).length, 1)
  assert.equal(source.includes('onStartVisualScan'), false)
  assert.equal(source.includes('onStartTechScan'), false)
  assert.equal(source.includes('Visual QA\n'), false)
  assert.equal(source.includes('Tech QA\n'), false)
})

test('input panel keeps scan scope copy out of the sidebar', () => {
  const source = fs.readFileSync('src/components/InputPanel.jsx', 'utf8')
  assert.equal(source.includes('실행 범위'), false)
  assert.equal(source.includes('MVP'), false)
  assert.equal(source.includes('/api/scan'), false)
  assert.equal(source.includes('/api/visual/payload'), false)
  assert.equal(source.includes('Web URL을 입력하면 Tech QA를 실행합니다. Figma URL을 함께 입력하면 Visual QA도 실행합니다.'), false)
  assert.equal(source.includes('lead-text'), false)
  assert.equal(source.includes('Figma Frame URL을 함께 입력하면 Visual QA도 실행합니다.'), false)
  assert.equal(source.includes('Figma URL <span className="field-label-note">Visual QA용</span>'), true)
  assert.equal(source.includes('Figma Frame URL <span className="field-label-note">Visual QA용</span>'), false)
})

test('input panel keeps sidebar intro and lower form layout without changing handlers', () => {
  const source = fs.readFileSync('src/components/InputPanel.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(source.includes('sidebar-topbar'), true)
  assert.equal(source.includes('sidebar-content'), true)
  assert.equal(source.includes('sidebar-intro'), true)
  assert.equal(source.includes('sidebar-description'), true)
  assert.equal(source.includes('sidebar-input-section'), true)
  assert.equal(source.includes('Web 페이지의 기술 품질을 점검하고, Figma 시안과 실제 화면의 콘텐츠·디자인 차이를 AI로 함께 검수합니다.'), true)
  assert.equal(source.includes('value={url}'), true)
  assert.equal(source.includes('value={figmaUrl}'), true)
  assert.equal(source.includes('onChange={(event) => onUrlChange(event.target.value)}'), true)
  assert.equal(source.includes('onChange={(event) => onFigmaUrlChange(event.target.value)}'), true)
  assert.equal(source.includes('onSubmit={handleSubmit}'), true)
  assert.equal(source.includes('onStartScan()'), true)
  assert.equal(source.includes('disabled={isScanning}'), true)
  assert.equal(source.includes("{isScanning ? '검사 중...' : '검사 시작'}"), true)
  assert.equal(css.includes('display: flex;'), true)
  assert.equal(css.includes('flex-direction: column;'), true)
  assert.equal(css.includes('.control-panel .sidebar-input-section'), true)
  assert.equal(css.includes('margin-top: auto;'), true)
})

test('app default scan flow calls integrated qa endpoint only', () => {
  const source = fs.readFileSync('src/App.jsx', 'utf8')
  assert.equal(source.includes("fetch('/api/qa/run'"), true)
  assert.equal(source.includes("fetch('/api/ai-review/from-payload'"), true)
  assert.equal(source.includes("fetch('/api/scan'"), false)
  assert.equal(source.includes("fetch('/api/visual/payload'"), false)
  assert.equal(source.includes('pageTitle={techResult?.pageTitle}'), true)
})

test('app keeps result tabs neutral before scan and disables unavailable scopes', () => {
  const appSource = fs.readFileSync('src/App.jsx', 'utf8')
  const tabSource = fs.readFileSync('src/components/WorkspaceTabs.jsx', 'utf8')
  const emptySource = fs.readFileSync('src/components/EmptyState.jsx', 'utf8')
  assert.equal(appSource.includes("useState('overview')"), true)
  assert.equal(appSource.includes('mode="overview"'), true)
  assert.equal(appSource.includes('disabledTabs={{ visual: !isVisualTabEnabled, tech: !isTechTabEnabled }}'), true)
  assert.equal(appSource.includes("setActiveTab(frameUrl ? 'visual' : 'tech')"), true)
  assert.equal(tabSource.includes('disabled={Boolean(disabledTabs[tab.id])}'), true)
  assert.equal(emptySource.includes("if (isOverview) return 'PagePilot QA'"), true)
  assert.equal(emptySource.includes('Web URL만 입력하면 Tech QA를 실행합니다.'), true)
  assert.equal(emptySource.includes('Figma URL을 함께 입력하면 Visual QA도 같이 실행합니다.'), true)
})

test('history panel supports new scan and item deletion without navigation reload', () => {
  const appSource = fs.readFileSync('src/App.jsx', 'utf8')
  const historySource = fs.readFileSync('src/components/HistoryPanel.jsx', 'utf8')
  assert.equal(historySource.includes('새 검사'), true)
  assert.equal(historySource.includes('검사 기록'), true)
  assert.equal(historySource.includes('저장된 QA 결과를 다시 확인할 수 있습니다.'), true)
  assert.equal(historySource.includes('history-toolbar'), true)
  assert.equal(historySource.includes('disabled={isScanning}'), true)
  assert.equal(historySource.includes("event.stopPropagation()"), true)
  assert.equal(historySource.includes('이 검사 기록을 삭제할까요?'), true)
  assert.equal(historySource.includes('aria-label="검사 기록 삭제"'), true)
  assert.equal(historySource.includes('history-delete-button'), true)
  assert.equal(appSource.includes("setActiveTab('overview')"), true)
  assert.equal(appSource.includes('setSelectedHistoryId(item.id)'), true)
  assert.equal(appSource.includes('deleteHistoryItem(id)'), true)
  assert.equal(appSource.includes('window.location'), false)
  assert.equal(appSource.includes('location.reload'), false)
})

test('empty state uses different scanning stages for tech-only and integrated runs', () => {
  const source = fs.readFileSync('src/components/EmptyState.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(source.includes('접속, 링크, 이미지 및 메타 정보를 검사하고 있습니다.'), true)
  assert.equal(source.includes('모바일과 기술 품질 항목을 확인하고 있습니다.'), true)
  assert.equal(source.includes('Web 페이지와 검사 데이터를 수집하고 있습니다.'), true)
  assert.equal(source.includes('시안 정보와 Web 데이터를 비교하고 있습니다.'), true)
  assert.equal(source.includes('AI가 확인된 차이를 최종 검토하고 있습니다.'), true)
  assert.equal(css.includes('grid-template-columns: 18px minmax(0, 1fr);'), true)
  assert.equal(source.includes('scan-stage-row'), true)
  assert.equal(source.includes('scan-stage-dot'), true)
  assert.equal(source.includes('scan-stage-text'), true)
  assert.equal(css.includes('white-space: nowrap;'), true)
  assert.equal(css.includes('.scan-stage-list li::before {\n  display: none;'), true)
})

test('visual accordions share closed row height and hide collapsed bodies', () => {
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(css.includes('.visual-detail-accordion > summary,'), true)
  assert.equal(css.includes('.full-findings-accordion > summary,'), true)
  assert.equal(css.includes('.developer-info-accordion > summary'), true)
  assert.equal(css.includes('min-height: 58px;'), true)
  assert.equal(css.includes('.developer-info-accordion:not([open]) > .developer-info-body'), true)
  assert.equal(css.includes('display: none;'), true)
})

test('visual panel keeps AI review report UI out of the default view', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  assert.equal(source.includes('배포 판단'), false)
  assert.equal(source.includes('AI 종합 검토'), false)
  assert.equal(source.includes('ReleaseDecisionCard'), false)
  assert.equal(source.includes('KeyIssueList'), false)
  assert.equal(source.includes('MetricPill'), false)
  assert.equal(source.includes('createVisualDifferenceReport(result, aiReview)'), false)
  assert.equal(source.includes('createVisualDisplayIssues(result, aiReview)'), true)
  assert.equal(source.includes('rawVisionCount=${differenceMeta.rawVisionCount}'), true)
  assert.equal(source.includes('createVisualQaTitle({ pageTitle, result })'), true)
  assert.equal(source.includes('AI 시각 비교'), false)
  assert.equal(source.includes('AI 분석 요약'), true)
  assert.equal(source.includes('visualDifferences'), false)
  assert.equal(source.includes('회신 초안 보기'), false)
  assert.equal(source.includes('clientReplyDraft'), false)
})

test('visual panel hides severity badges in default difference cards', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(source.includes('formatSeverity'), false)
  assert.equal(source.includes('difference-severity'), false)
  assert.equal(source.includes('Critical'), false)
  assert.equal(source.includes('Warning'), false)
  assert.equal(source.includes('Check'), false)
  assert.equal(css.includes('.difference-severity'), false)
  assert.equal(source.includes('item.severity'), false)
  assert.equal(source.includes('figmaValue'), true)
  assert.equal(source.includes('webValue'), true)
})

test('visual panel removes inaccurate image position highlighting', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(source.includes('scrollTo('), false)
  assert.equal(source.includes('highlightRatio'), false)
  assert.equal(source.includes('setHighlight'), false)
  assert.equal(source.includes('image-highlight-band'), false)
  assert.equal(source.includes('createRatioScrollSynchronizer'), false)
  assert.equal(css.includes('image-highlight-band'), false)
})

test('visual panel uses restored stable image comparison shell', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(source.includes('visual-comparison-viewport'), true)
  assert.equal(source.includes('visual-comparison-columns'), true)
  assert.equal(source.includes('onScroll='), false)
  assert.equal(css.includes('.visual-comparison-viewport'), true)
  assert.equal(css.includes('.visual-comparison-columns'), true)
  assert.equal(fs.existsSync('src/utils/visualScrollSync.js'), false)
})

test('empty state separates pre-scan guidance from scanning progress', () => {
  const source = fs.readFileSync('src/components/EmptyState.jsx', 'utf8')
  assert.equal(source.includes("return isTech ? 'Tech QA' : 'Visual QA'"), true)
  assert.equal(source.includes('Web URL과 Figma URL을 입력하세요. Figma 시안과 Web 페이지를 비교합니다.'), true)
  assert.equal(source.includes('Web URL을 입력하고 검사를 시작하세요. 페이지 접속 상태와 기술 항목을 검사합니다.'), true)
  assert.equal(source.includes('Playwright:'), false)
  assert.equal(source.includes('Figma API:'), false)
  assert.equal(source.includes('Canonical:'), false)
  assert.equal(source.includes('AI 멀티모달:'), false)
  assert.equal(source.includes('결과 생성:'), false)
  assert.equal(source.includes('1차 수집'), false)
  assert.equal(source.includes('Web 페이지를 수집하고 있습니다.'), true)
  assert.equal(source.includes('2차 비교'), false)
  assert.equal(source.includes('시안 정보와 Web 데이터를 비교하고 있습니다.'), true)
  assert.equal(source.includes('3차 검증'), false)
  assert.equal(source.includes('구조와 콘텐츠의 차이를 검증하고 있습니다.'), true)
  assert.equal(source.includes("title: '최종 검토'"), false)
  assert.equal(source.includes('AI가 확인된 차이를 최종 검토하고 있습니다.'), true)
  assert.equal(source.includes("title: '결과 정리'"), false)
  assert.equal(source.includes('최종 QA 결과를 정리하고 있습니다.'), true)
  assert.equal(source.includes('<strong>{stage.title}</strong>'), false)
  assert.equal(source.includes('<span>{stage.description}</span>'), false)
  assert.equal(source.includes('AI Vision'), false)
})

test('visual panel renders simplified default sections and folded detail analysis', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const imageIndex = source.indexOf('Figma / Web 이미지 비교')
  const differenceIndex = source.indexOf('핵심 차이')
  const fullIndex = source.indexOf('전체 발견 항목 보기')
  const detailIndex = source.indexOf('<details className="detail-card visual-detail-accordion">')
  assert.equal(source.includes('visual-severity-grid'), false)
  assert.equal(source.includes('<details className="detail-card visual-card-list-card" open>'), false)
  assert.equal(source.includes('<section className="visual-detail-panel"'), false)
  assert.equal(source.includes('상세 분석 보기'), true)
  assert.equal(source.includes('AI 멀티모달 검증 완료'), true)
  assert.equal(source.includes('Playwright 수집 완료'), true)
  assert.equal(source.includes('Figma API 비교 완료'), true)
  assert.equal(source.includes('Canonical 2차 검증 완료'), true)
  assert.equal(source.includes('AI 멀티모달 최종 검토 완료'), true)
  assert.equal(source.includes('<details className="detail-card visual-detail-accordion" open>'), false)
  assert.equal(imageIndex > -1, true)
  assert.equal(differenceIndex > imageIndex, true)
  assert.equal(fullIndex > differenceIndex, true)
  assert.equal(detailIndex > fullIndex, true)
  assert.equal(source.includes('규칙 기반 Critical / Warning / Check'), false)
  assert.equal(source.includes('규칙 기반 검사 상세'), false)
  assert.equal(source.includes('RuleIssueList'), false)
  assert.equal(source.includes('visual-detail-stack'), true)
  assert.equal(source.includes('visual-sub-accordion'), true)
  assert.equal(source.includes('<DetailAccordion title="Hero"'), true)
  assert.equal(source.includes('<DetailAccordion title="CTA"'), true)
  assert.equal(source.includes('<DetailAccordion title="Price / Numeric"'), true)
  assert.equal(source.includes('<DetailAccordion title="Media"'), true)
  assert.equal(source.includes('<DetailAccordion title="Text"'), true)
  assert.equal(source.includes('<DetailAccordion title="System"'), true)
  assert.equal(source.includes('<details className="visual-sub-accordion" open>'), false)
  assert.equal(source.includes('review?.summary'), false)
  assert.equal(source.includes('Payload Version'), true)
  assert.equal(source.includes('Raw Vision Count'), true)
  assert.equal(source.includes('Final Report Items'), true)
  assert.equal(source.includes('Comparison Differences'), true)
  assert.equal(source.includes('AI Visual Differences'), true)
  assert.equal(source.includes('CTA Evidence'), true)
  assert.equal(source.includes('Media Evidence'), true)
  assert.equal(source.includes('Price/Numeric Evidence'), true)
  assert.equal(source.includes('Display Candidates'), true)
  assert.equal(source.includes('Display Groups'), true)
  assert.equal(source.includes('Grouped Issue Count'), true)
  assert.equal(source.includes('Exact Duplicate Removed'), true)
  assert.equal(source.includes('Core Issue Count'), true)
  assert.equal(source.includes('Excluded From Core'), true)
  assert.equal(source.includes('Engine Data Deleted'), true)
  assert.equal(source.includes('displayCount'), false)
  assert.equal(source.includes('UI 표시 개수'), true)
  assert.equal(source.includes('나머지 {remainingCount}건 더보기'), false)
  assert.equal(source.includes('items.slice'), false)
  assert.equal(source.includes('remainingCount'), false)
  assert.equal(source.includes('getDifferenceCategoryClass'), true)
  assert.equal(source.includes('difference-category-chip'), true)
  assert.equal(source.includes('is-text'), true)
  assert.equal(source.includes('is-cta'), true)
  assert.equal(source.includes('is-media'), true)
  assert.equal(source.includes('is-price'), true)
  assert.equal(source.includes('is-missing'), true)
  assert.equal(source.includes('AI Vision'), false)
  assert.equal(source.includes('<span>{item.description}</span>'), false)
})

test('visual panel completed AI meta only shows model and duration by default', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const completeStart = source.indexOf('function AiMultimodalComplete')
  const completeEnd = source.indexOf('function AiVisionSummary')
  const completeSource = source.slice(completeStart, completeEnd)
  assert.equal(completeSource.includes('label="모델"'), true)
  assert.equal(completeSource.includes('label="처리 시간"'), true)
  assert.equal(completeSource.includes('label="이미지"'), false)
  assert.equal(completeSource.includes('label="Fallback"'), false)
  assert.equal(completeSource.includes('label="최종 차이"'), false)
  assert.equal(source.includes('<AiMultimodalComplete aiReview={aiReview} />'), true)
})

test('visual panel renders the integrated display issue source without default list limits', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  assert.equal(source.includes('const displayIssues = createVisualDisplayIssues(result, aiReview)'), true)
  assert.equal(source.includes('const coreIssues = createCoreVisualIssues(displayIssues)'), true)
  assert.equal(source.includes('const coreIssueGroups = createVisualIssueGroups(coreIssues, { mergeReadableAreas: true })'), true)
  assert.equal(source.includes('const fullIssueGroups = createVisualIssueGroups(displayIssues)'), true)
  assert.equal(source.includes('<IssueGroupList groups={coreIssueGroups} />'), true)
  assert.equal(source.includes('<IssueGroupList groups={fullIssueGroups} compact />'), true)
  assert.equal(source.includes('formatGroupIssueCount(fullIssueGroups.length'), true)
  assert.equal(source.includes('formatIssueCountSummary(coreGroupMeta.groupedIssueCount ?? coreIssues.length)'), true)
  assert.equal(source.includes('displayIssues.slice'), false)
  assert.equal(source.includes('issueGroups.slice'), false)
  assert.equal(source.includes('displayCount'), false)
})

test('visual panel renders grouped issue cards without hiding the issue list in details', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  const groupedIndex = source.indexOf('<IssueGroupList groups={coreIssueGroups} />')
  const fullIndex = source.indexOf('<IssueGroupList groups={fullIssueGroups} compact />')
  const detailIndex = source.indexOf('<details className="detail-card visual-detail-accordion">')
  assert.equal(source.includes('핵심 차이'), true)
  assert.equal(source.includes('전체 발견 항목 보기'), true)
  assert.equal(source.includes('issue-group-list'), true)
  assert.equal(source.includes('issue-group-card'), true)
  assert.equal(source.includes('issue-group-items'), true)
  assert.equal(source.includes('issue-group-values'), true)
  assert.equal(groupedIndex > -1 && fullIndex > groupedIndex && detailIndex > fullIndex, true)
  assert.equal(css.includes('.issue-group-list'), true)
  assert.equal(css.includes('.issue-group-card'), true)
  assert.equal(css.includes('.issue-group-item::before'), true)
  assert.equal(css.includes('.issue-group-item.is-text .difference-category-chip'), true)
  assert.equal(css.includes('.issue-group-values'), true)
})
