import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

function readSource(filePath) {
  return fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n')
}

function getDeclarationValue(cssBlock, propertyName) {
  const escapedPropertyName = propertyName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = cssBlock.match(new RegExp(`(?:^|\\n)\\s*${escapedPropertyName}:\\s*([^;]+);`))
  return match ? match[1].trim() : ''
}

function isMintFill(value) {
  return value.includes('var(--start-mint') || value.includes('#43c4ad') || value.includes('#54cfb8')
}

test('input panel exposes one scan start button only', () => {
  const source = readSource('src/components/InputPanel.jsx')
  const startSource = readSource('src/components/QaStartScreen.jsx')
  assert.equal((source.match(/type="submit"/g) || []).length, 1)
  assert.equal((startSource.match(/type="submit"/g) || []).length, 1)
  assert.equal(source.includes('v0.3'), false)
  assert.equal(source.includes('v0.6.0'), true)
  assert.equal(startSource.includes('v0.6.0'), true)
  assert.equal(source.includes('onStartVisualScan'), false)
  assert.equal(source.includes('onStartTechScan'), false)
  assert.equal(source.includes('Visual QA\n'), false)
  assert.equal(source.includes('Tech QA\n'), false)
})

test('input panel keeps scan scope copy out of the sidebar', () => {
  const source = readSource('src/components/InputPanel.jsx')
  const startSource = readSource('src/components/QaStartScreen.jsx')
  assert.equal(source.includes('실행 범위'), false)
  assert.equal(source.includes('MVP'), false)
  assert.equal(source.includes('/api/scan'), false)
  assert.equal(source.includes('/api/visual/payload'), false)
  assert.equal(source.includes('Web URL을 입력하면 Tech QA를 실행합니다. Figma URL을 함께 입력하면 Visual QA도 실행합니다.'), false)
  assert.equal(source.includes('lead-text'), false)
  assert.equal(source.includes('Figma Frame URL을 함께 입력하면 Visual QA도 실행합니다.'), false)
  assert.equal(source.includes('Figma URL <span className="field-label-note">Visual QA용</span>'), true)
  assert.equal(source.includes('Figma Frame URL <span className="field-label-note">Visual QA용</span>'), false)
  assert.equal(startSource.includes('기술과 디자인, 한 번에 검증하세요.'), true)
  assert.equal(startSource.includes('AI 기반 Tech QA와 Visual QA로 웹페이지의 품질과 디자인 차이를 빠르게 확인하세요.'), true)
  assert.equal(startSource.includes('QA, Start here.'), false)
  assert.equal(startSource.includes('Web QA를 하나로'), false)
  assert.equal(startSource.includes('AI 기반 Tech QA와 Visual QA를 하나의 리포트에서 확인하세요.'), false)
  assert.equal(startSource.includes('AI 기반 Web QA 플랫폼'), false)
})

test('input panel keeps sidebar intro and lower form layout without changing handlers', () => {
  const source = readSource('src/components/InputPanel.jsx')
  const optionComponentSource = readSource('src/components/TechScanOptions.jsx')
  const optionSource = readSource('shared/techScanOptions.js')
  assert.equal(source.includes('sidebar-topbar'), true)
  assert.equal(source.includes('sidebar-content'), true)
  assert.equal(source.includes('sidebar-intro'), true)
  assert.equal(source.includes('sidebar-description'), true)
  assert.equal(source.includes('sidebar-input-section'), true)
  assert.equal(source.includes('Web 페이지의 기술 품질을 점검하고, Figma 시안과 실제 화면의 콘텐츠·디자인 차이를 AI로 함께 검수합니다.'), true)
  assert.equal(source.includes('value={url}'), true)
  assert.equal(source.includes('value={figmaUrl}'), true)
  assert.equal(source.includes('type="url"'), true)
  assert.equal(source.includes('onChange={(event) => onUrlChange(event.target.value)}'), true)
  assert.equal(source.includes('onChange={(event) => onFigmaUrlChange(event.target.value)}'), true)
  assert.equal(source.includes('onSubmit={handleSubmit}'), true)
  assert.equal(source.includes('onStartScan()'), true)
  assert.equal(source.includes('disabled={isScanning}'), true)
  assert.equal(source.includes("{isScanning ? '검사 중...' : '검사 시작'}"), true)
  assert.equal(optionComponentSource.includes('Tech QA 선택 옵션'), true)
  assert.equal(source.includes('전체 선택'), false)
  assert.equal(optionComponentSource.includes('모두 선택'), true)
  assert.equal(optionComponentSource.includes('주요 검사'), true)
  assert.equal(source.includes('선택 검사 제어'), false)
  assert.equal(optionComponentSource.includes('tech-scan-options'), true)
  assert.equal(optionComponentSource.includes('tech-scan-options-summary-action'), false)
  assert.equal(optionComponentSource.includes('tech-scan-option-toggle-row'), true)
  assert.equal(optionComponentSource.includes('TECH_SCAN_OPTION_GROUPS.map'), true)
  assert.equal(optionSource.includes("label: 'Scroll QA'"), true)
  assert.equal(optionSource.includes("label: 'Responsive QA'"), true)
  assert.equal(optionSource.includes("label: 'Download QA'"), true)
  assert.equal(optionSource.includes("label: 'Cookie QA'"), true)
  assert.equal(optionSource.includes("label: 'Image QA'"), true)
  assert.equal(optionSource.includes("label: 'Performance QA'"), true)
  assert.equal(optionSource.includes("label: 'SEO QA'"), true)
  assert.equal(optionSource.indexOf("label: 'Modal QA'") < optionSource.indexOf("label: 'Scroll QA'"), true)
  assert.equal(optionSource.indexOf("label: 'Scroll QA'") < optionSource.indexOf("label: 'Responsive QA'"), true)
  assert.equal(optionSource.indexOf("label: 'Responsive QA'") < optionSource.indexOf("label: 'Download QA'"), true)
  assert.equal(optionSource.indexOf("label: 'Download QA'") < optionSource.indexOf("label: 'Cookie QA'"), true)
  assert.equal(optionSource.indexOf("label: 'Cookie QA'") < optionSource.indexOf("label: 'Image QA'"), true)
  assert.equal(optionSource.indexOf("label: 'Image QA'") < optionSource.indexOf("label: 'Performance QA'"), true)
  assert.equal(optionSource.indexOf("label: 'Performance QA'") < optionSource.indexOf("label: 'SEO QA'"), true)
  assert.equal(optionSource.indexOf("label: 'SEO QA'") < optionSource.indexOf("label: '마크업 및 접근성 검사'"), true)
  assert.equal(optionSource.includes("key: 'basic'"), false)
  assert.equal(optionSource.includes("key: 'main'"), false)
  assert.equal(optionComponentSource.includes('checked={draftAllSelected}'), true)
  assert.equal(optionComponentSource.includes('indeterminate'), false)
  assert.equal(optionComponentSource.includes('checked={draftOptions[option.key] === true}'), true)
  assert.equal(optionComponentSource.includes('id="tech-scan-option-basic"'), false)
  assert.equal(optionComponentSource.includes('tech-scan-option-basic-card'), false)
  assert.equal(optionComponentSource.includes('항상 실행됨'), false)
  assert.equal(optionComponentSource.includes('<div className="tech-scan-options" aria-label="Tech QA 옵션">'), true)
  assert.equal(optionComponentSource.includes('const [isTechOptionsOpen, setIsTechOptionsOpen] = useState(false)'), true)
  assert.equal(optionComponentSource.includes('className="tech-scan-options-trigger"'), true)
  assert.equal(optionComponentSource.includes('옵션 변경'), false)
  assert.equal(optionComponentSource.includes('tech-scan-options-trigger-arrow'), false)
  assert.equal(optionComponentSource.includes('tech-scan-options-trigger-action'), false)
  assert.equal(optionComponentSource.includes('tech-scan-options-trigger-icon'), false)
  assert.equal(optionComponentSource.includes('검사 범위 변경'), false)
  assert.equal(optionComponentSource.includes('<strong>선택 검사 제어</strong>'), false)
  assert.equal(optionComponentSource.includes('aria-haspopup="dialog"'), true)
  assert.equal(optionComponentSource.includes('role="dialog"'), true)
  assert.equal(optionComponentSource.includes('aria-modal="true"'), true)
  assert.equal(optionComponentSource.includes('<label className="tech-scan-option-row tech-scan-option-toggle-row" htmlFor="tech-scan-option-all">'), true)
  assert.equal(optionComponentSource.includes('className="tech-scan-option-group tech-scan-option-basic-card"'), false)
  assert.equal(optionComponentSource.indexOf('tech-scan-options-dialog-header') < optionComponentSource.indexOf('tech-scan-option-toggle-row'), true)
  assert.equal(optionComponentSource.indexOf('tech-scan-option-toggle-row') < optionComponentSource.indexOf('TECH_SCAN_OPTION_GROUPS.map'), true)
  assert.equal(optionComponentSource.indexOf('모두 선택') < optionComponentSource.indexOf('TECH_SCAN_OPTION_GROUPS.map'), true)
  assert.equal(optionSource.indexOf("label: 'URL 검사'") < optionSource.indexOf("label: '클릭 동작 검사'"), true)
  assert.equal(optionSource.indexOf("label: 'Modal QA'") < optionSource.indexOf("label: 'Scroll QA'"), true)
  assert.equal(optionSource.indexOf("label: 'SEO QA'") < optionSource.indexOf("label: '마크업 및 접근성 검사'"), true)
})

test('input panel structures group-only tech scan options without changing scan payload', () => {
  const source = readSource('src/components/InputPanel.jsx')
  const optionComponentSource = readSource('src/components/TechScanOptions.jsx')
  const startSource = readSource('src/components/QaStartScreen.jsx')
  const appSource = readSource('src/App.jsx')
  const css = readSource('src/App.css')
  const optionUiSource = `${optionComponentSource}\n${source}\n${startSource}`

  assert.equal(optionUiSource.includes('검사 프리셋'), false)
  assert.equal(optionUiSource.includes('tech-scan-preset-select'), false)
  assert.equal(optionUiSource.includes('value={selectedPresetId}'), false)
  assert.equal(optionUiSource.includes('disabled={isScanning}'), true)
  assert.equal(optionUiSource.includes('onChange={(event) => handlePresetChange(event.target.value)}'), false)
  assert.equal(optionUiSource.includes('TECH_SCAN_CUSTOM_PRESET_ID'), false)
  assert.equal(optionUiSource.includes('getTechScanPresetId'), false)
  assert.equal(optionUiSource.includes('getTechScanOptionsForPreset'), false)
  assert.equal(optionComponentSource.includes('openTechOptions'), true)
  assert.equal(optionComponentSource.includes('closeTechOptions'), true)
  assert.equal(optionComponentSource.includes('applyTechOptions'), true)
  assert.equal(optionComponentSource.includes('if (isScanning) return'), true)
  assert.equal(optionComponentSource.includes('setDraftOptions(techScanOptions)'), true)
  assert.equal(optionUiSource.includes('IndeterminateCheckbox'), false)
  assert.equal(optionUiSource.includes('getTechScanSelectionState'), false)
  assert.equal(optionUiSource.includes('applyTechScanGroupSelection'), false)
  assert.equal(optionComponentSource.includes('group.optionKeys.some((key) => draftOptions[key] === true)'), true)
  assert.equal(optionComponentSource.includes('onChange={(event) => handleToggleGroup(group.optionKeys, event.target.checked)}'), true)
  assert.equal(optionComponentSource.includes('tech-scan-option-group-chevron'), false)
  assert.equal(optionComponentSource.includes('setOpenOptionGroups'), false)
  assert.equal(optionComponentSource.includes('tech-scan-options-body'), true)
  assert.equal(optionComponentSource.includes('tech-scan-option-groups'), true)
  assert.equal(source.indexOf('id="target-url"') < source.indexOf('<TechScanOptions'), true)
  assert.equal(source.indexOf('id="figma-frame-url"') < source.indexOf('<TechScanOptions'), true)
  assert.equal(source.indexOf('<TechScanOptions') < source.indexOf('<button className="primary-button" type="submit" disabled={isScanning}>'), true)
  assert.equal((source.match(/type="submit"/g) || []).length, 1)
  assert.equal(appSource.includes('body: JSON.stringify({ webUrl, figmaUrl, scanOptions })'), true)
  assert.equal(appSource.includes('preset'), false)
  assert.equal(css.includes('.tech-scan-options-body'), true)
  assert.equal(css.includes('max-height: clamp'), false)
  assert.equal(css.includes('.url-input'), true)
  assert.equal(css.includes('.url-input.scan-input'), true)
  assert.equal(css.includes('flex: none;'), true)
  assert.equal(css.includes(`.control-panel .primary-button {
  min-height: 46px;`), false)
  assert.equal(css.includes('padding: 10px 12px;'), true)
  assert.equal(css.includes('.tech-scan-option-group-summary'), true)
  assert.equal(css.includes('.tech-scan-group-checkbox'), true)
  assert.equal(css.includes('.scan-form > .primary-button'), true)
  assert.equal(css.includes('flex: 0 0 auto;'), true)
  assert.equal(css.includes('margin-top: auto;'), true)
})

test('tech scan options use modal trigger with draft apply without changing payload keys', () => {
  const optionComponentSource = readSource('src/components/TechScanOptions.jsx')
  const optionSource = readSource('shared/techScanOptions.js')
  const appSource = readSource('src/App.jsx')
  const css = readSource('src/App.css')

  assert.equal(optionComponentSource.includes('className="tech-scan-options-trigger"'), true)
  assert.equal(optionComponentSource.includes('aria-haspopup="dialog"'), true)
  assert.equal(optionComponentSource.includes('aria-expanded={isTechOptionsOpen}'), true)
  assert.equal(optionComponentSource.includes('role="dialog"'), true)
  assert.equal(optionComponentSource.includes('aria-modal="true"'), true)
  assert.equal(optionComponentSource.includes('aria-labelledby={titleId}'), true)
  assert.equal(optionComponentSource.includes('aria-describedby={descriptionId}'), true)
  assert.equal(optionComponentSource.includes('aria-label="닫기"'), true)
  assert.equal(optionComponentSource.includes('event.key === \'Escape\''), true)
  assert.equal(optionComponentSource.includes('handleBackdropMouseDown'), true)
  assert.equal(optionComponentSource.includes('event.target !== event.currentTarget'), true)
  assert.equal(optionComponentSource.includes("import { createPortal } from 'react-dom'"), true)
  assert.equal(optionComponentSource.includes('), document.body) : null}'), true)
  assert.equal(optionComponentSource.includes('triggerRef.current?.focus()'), true)
  assert.equal(optionComponentSource.includes('document.body.style.overflow = \'hidden\''), true)
  assert.equal(optionComponentSource.includes('window.addEventListener(\'keydown\', handleWindowKeyDown, true)'), true)
  assert.equal(optionComponentSource.includes('keepFocusInsideDialog(event, dialogRef.current)'), true)
  assert.equal(optionComponentSource.includes('const [draftOptions, setDraftOptions] = useState(techScanOptions)'), true)
  assert.equal(optionComponentSource.includes('setDraftOptions(techScanOptions)'), true)
  assert.equal(optionComponentSource.includes('onTechScanOptionsChange({ ...draftOptions })'), true)
  assert.equal(optionComponentSource.includes('추가 Tech QA 선택 옵션 없음'), true)
  assert.equal(optionComponentSource.includes('${selectedCount}개 Tech QA 선택 옵션 적용 중'), true)
  assert.equal(optionComponentSource.includes('14개 선택 옵션 적용 중'), false)
  assert.equal(optionComponentSource.includes('tech-scan-options-primary'), true)
  assert.equal(optionComponentSource.includes('tech-scan-options-secondary-row'), true)
  assert.equal(optionComponentSource.includes('tech-scan-options-link'), true)
  assert.equal(optionComponentSource.includes('tech-scan-options-chevron'), true)
  const triggerButtonStart = optionComponentSource.lastIndexOf('<button', optionComponentSource.indexOf('className="tech-scan-options-trigger"'))
  const triggerButtonSource = optionComponentSource.slice(triggerButtonStart, optionComponentSource.indexOf('</button>', triggerButtonStart))
  assert.equal(triggerButtonSource.includes('tech-scan-options-status-check'), false)
  assert.equal(triggerButtonSource.includes('tech-scan-options-link'), true)
  assert.equal(triggerButtonSource.includes('tech-scan-options-chevron'), true)
  assert.equal(optionComponentSource.includes('〉'), false)
  assert.equal(optionComponentSource.includes('&gt;'), false)
  assert.equal(optionComponentSource.includes('Tech QA 옵션 선택하기'), false)
  assert.equal(optionComponentSource.includes('항상 실행됨'), false)
  assert.equal(optionComponentSource.includes('tech-scan-option-toggle-title'), false)
  assert.equal(optionComponentSource.includes('tech-scan-option-toggle-control'), true)
  assert.equal(optionComponentSource.includes('aria-label="선택 검사 모두 선택"'), true)
  assert.equal(optionComponentSource.includes('tech-scan-options-trigger-action'), false)
  assert.equal(optionComponentSource.includes('tech-scan-options-trigger-icon'), false)
  assert.equal(optionComponentSource.includes('checked={draftAllSelected}'), true)
  assert.equal(optionComponentSource.includes('checked={draftOptions[option.key] === true}'), true)
  assert.equal(optionComponentSource.includes('checked={isGroupChecked}'), true)
  assert.equal(optionComponentSource.includes('checked\n                    disabled\n                    readOnly'), false)
  assert.equal(optionComponentSource.includes('indeterminate'), false)
  assert.equal(optionComponentSource.includes('tech-scan-preset-select'), false)
  assert.equal(optionComponentSource.includes('getTechScanOptionsForPreset'), false)
  assert.equal(optionSource.includes('TECH_SCAN_OPTION_KEYS'), true)
  assert.equal(appSource.includes('body: JSON.stringify({ webUrl, figmaUrl, scanOptions })'), true)
  assert.equal(appSource.includes('preset'), false)
  assert.equal(css.includes('--start-option-muted: #718087;'), true)
  assert.equal(css.includes('--start-option-success: var(--start-success);'), true)
  assert.equal(css.includes('color: var(--start-option-muted);'), true)
  assert.equal(css.includes('color: var(--start-option-success);'), true)
  assert.equal(css.includes('accent-color: #2e5da7;'), false)
  assert.equal(css.includes('background: var(--start-mint, #43c4ad);'), true)
  assert.equal(css.includes('border: solid #ffffff;'), true)
  assert.equal(css.includes('.tech-scan-options-backdrop'), true)
  assert.equal(css.includes('.tech-scan-options-dialog'), true)
  assert.equal(css.includes('max-height: min(76vh, 720px);'), true)
  assert.equal(css.includes('width: min(620px, calc(100vw - 40px));'), true)
  assert.equal(css.includes('place-items: center;'), true)
  assert.equal(css.includes('max-height: 82vh;'), true)
  assert.equal(css.includes('qaSheetPanelIn'), true)
  assert.equal(css.includes('.tech-scan-option-toggle-row'), true)
  assert.equal(css.includes('background: transparent;'), true)
})

test('idle start screen uses centered progressive onboarding without changing request contracts', () => {
  const appSource = readSource('src/App.jsx')
  const startSource = readSource('src/components/QaStartScreen.jsx')
  const inputSource = readSource('src/components/InputPanel.jsx')
  const optionSource = readSource('src/components/TechScanOptions.jsx')
  const css = readSource('src/App.css')

  assert.equal(appSource.includes("import QaStartScreen from './components/QaStartScreen'"), true)
  assert.equal(appSource.includes("import { confirmWebUrlInput, createDebouncedWebUrlConfirmScheduler, createPublicWebUrlState, createWebUrlInputState, isValidHttpUrl } from './utils/scanSession'"), true)
  assert.equal(appSource.includes('const [isWebUrlConfirmed, setIsWebUrlConfirmed] = useState(false)'), true)
  assert.equal(appSource.includes('const webUrlState = createWebUrlInputState(url, { isConfirmed: isWebUrlConfirmed })'), true)
  assert.equal(appSource.includes('const isWebUrlReady = webUrlState.isConfirmed'), true)
  assert.equal(appSource.includes('const canStartWithWebUrl = webUrlState.isSyntacticallyValid'), true)
  assert.equal(appSource.includes('const startWebUrlState = createPublicWebUrlState(url)'), true)
  assert.equal(appSource.includes('const webUrl = startWebUrlState.normalizedUrl'), true)
  assert.equal(appSource.includes('setIsWebUrlConfirmed(true)'), true)
  assert.equal(appSource.includes('if (webUrl !== url.trim()) setUrl(webUrl)'), true)
  assert.equal(appSource.includes('const handleUrlBlur = () => {'), true)
  assert.equal(appSource.includes('const handleUrlConfirm = () => {'), true)
  assert.equal(appSource.includes('const nextState = confirmWebUrlInput(url)'), true)
  assert.equal(appSource.includes('useEffect(() => {'), true)
  assert.equal(appSource.includes('createDebouncedWebUrlConfirmScheduler({'), true)
  assert.equal(appSource.includes('setTimeoutFn: window.setTimeout'), true)
  assert.equal(appSource.includes('clearTimeoutFn: window.clearTimeout'), true)
  assert.equal(appSource.includes('scheduler.schedule(url)'), true)
  assert.equal(appSource.includes('return scheduler.cancel'), true)
  assert.equal(appSource.includes('setUrl((currentUrl) => currentUrl.trim() === nextState.rawValue.trim() ? nextState.inputValue : currentUrl)'), true)
  assert.equal(appSource.includes("const isIdleStartView = !isScanning && activeTab === 'overview' && !visualResult && !techResult && visualScanState === 'idle' && techScanState === 'idle'"), true)
  assert.equal(appSource.includes('if (isIdleStartView) {'), true)
  assert.equal(appSource.includes("import InputPanel from './components/InputPanel'"), false)
  assert.equal(appSource.includes('<InputPanel'), false)
  assert.equal(appSource.includes('canStartScan={canStartWithWebUrl}'), true)
  assert.equal(appSource.includes('isWebUrlReady={isWebUrlReady}'), true)
  assert.equal(appSource.includes('onUrlConfirm={handleUrlConfirm}'), true)
  assert.equal(appSource.includes('setIsWebUrlConfirmed(false)'), true)
  assert.equal(appSource.includes("setActiveTab(frameUrl ? 'visual' : 'tech')"), true)
  assert.equal(appSource.includes('requestQaRun(webUrl, frameUrl, techScanOptions)'), true)
  assert.equal(appSource.includes('body: JSON.stringify({ webUrl, figmaUrl, scanOptions })'), true)
  assert.equal(appSource.includes("fetch('/api/scan'"), false)
  assert.equal(appSource.includes("fetch('/api/visual/payload'"), false)
  const urlChangeSource = appSource.slice(appSource.indexOf('onUrlChange={(value) => {'), appSource.indexOf('      />', appSource.indexOf('onUrlChange={(value) => {')))
  assert.equal(urlChangeSource.includes('setUrl(value)'), true)
  assert.equal(urlChangeSource.includes('setIsWebUrlConfirmed(false)'), true)
  assert.equal(urlChangeSource.includes('setHasWebUrlBlurred(false)'), true)
  assert.equal(urlChangeSource.includes('if (!value.trim()) {'), true)
  assert.equal(urlChangeSource.includes("setFigmaUrl('')"), true)
  assert.equal(urlChangeSource.includes("setFigmaError('')"), true)
  assert.equal(urlChangeSource.includes("setInputError('')"), true)
  assert.equal(urlChangeSource.indexOf('if (!value.trim()) {') < urlChangeSource.indexOf("setFigmaUrl('')"), true)
  assert.equal(urlChangeSource.includes('setTechScanOptions'), false)

  const resetSource = appSource.slice(appSource.indexOf('const resetToNewScan = () => {'), appSource.indexOf('  const handleUrlBlur = () => {'))
  assert.equal(resetSource.includes('if (isScanning) return'), true)
  assert.equal(resetSource.includes('clearResultState()'), true)
  assert.equal(resetSource.includes("setUrl('')"), true)
  assert.equal(resetSource.includes("setFigmaUrl('')"), true)
  assert.equal(resetSource.includes('setIsWebUrlConfirmed(false)'), true)
  assert.equal(resetSource.includes('setHasWebUrlBlurred(false)'), true)
  assert.equal(resetSource.includes("setSelectedHistoryId('')"), true)
  assert.equal(resetSource.includes("setActiveTab('overview')"), true)
  assert.equal(resetSource.includes('setHistoryItems'), false)
  assert.equal(resetSource.includes('deleteHistoryItem'), false)
  assert.equal(resetSource.includes('setTechScanOptions'), false)

  assert.equal(startSource.includes('<div className="start-screen">'), true)
  assert.equal(startSource.includes('<header className="start-header"'), true)
  assert.equal(startSource.includes('<main className="start-main">'), true)
  assert.equal(startSource.includes('<section className="start-hero"'), true)
  assert.equal(startSource.includes('className="start-brand"'), true)
  assert.equal(startSource.includes('className="start-brand-symbol"'), false)
  assert.equal(startSource.includes('className="start-history-button"'), true)
  assert.equal(startSource.includes('onClick={onOpenHistory}'), true)
  assert.equal(startSource.indexOf('<header className="start-header"') < startSource.indexOf('<main className="start-main">'), true)
  assert.equal(startSource.indexOf('<button className="start-history-button"') < startSource.indexOf('<main className="start-main">'), true)
  assert.equal(startSource.indexOf('<main className="start-main">') < startSource.indexOf('<h1>기술과 디자인, 한 번에 검증하세요.</h1>'), true)
  assert.equal(startSource.includes('기술과 디자인, 한 번에 검증하세요.'), true)
  assert.equal(startSource.includes('<p>AI 기반 Tech QA와 Visual QA로 웹페이지의 품질과 디자인 차이를 빠르게 확인하세요.</p>'), true)
  assert.equal(startSource.includes('QA, Start here.'), false)
  assert.equal(startSource.includes('Web QA를 하나로'), false)
  assert.equal(startSource.includes('AI 기반 Tech QA와 Visual QA를 하나의 리포트에서 확인하세요.'), false)
  assert.equal(startSource.includes('<p>'), true)
  assert.equal(startSource.includes('<label className="start-label" htmlFor="target-url">'), false)
  assert.equal(startSource.includes('aria-label="Web URL"'), true)
  assert.equal(startSource.includes('placeholder="Tech QA를 진행할 Web URL을 입력하세요."'), true)
  assert.equal(startSource.includes('noValidate onSubmit={handleSubmit}'), true)
  assert.equal(startSource.includes('onBlur={onUrlBlur}'), true)
  assert.equal(startSource.includes('onKeyDown={handleUrlKeyDown}'), true)
  assert.equal(startSource.includes('onUrlConfirm()'), true)
  assert.equal(startSource.includes('start-composer start-url-composer'), true)
  assert.equal(startSource.includes('start-input-mark'), false)
  assert.equal(startSource.includes('start-url-check'), true)
  assert.equal(startSource.includes('Web URL이 확인되었습니다.'), true)
  assert.equal(startSource.includes('웹페이지가 확인되었습니다.'), false)
  assert.equal(startSource.includes('Visual QA도 진행할까요?'), true)
  assert.equal(startSource.includes('Figma 시안도 함께 비교할까요?'), false)
  assert.equal(startSource.includes('시안이 있다면 URL을 입력하세요. 선택 사항입니다.'), false)
  assert.equal(startSource.includes('<label className="start-label" htmlFor="figma-frame-url">'), false)
  assert.equal(startSource.includes('aria-label="Figma URL"'), true)
  assert.equal(startSource.includes('placeholder="Figma URL을 입력하세요. 선택 사항입니다."'), true)
  assert.equal(startSource.includes('isFigmaUrlReady'), true)
  assert.equal(startSource.includes('start-figma-check'), true)
  assert.equal(startSource.includes('const [shouldRenderProgressive, setShouldRenderProgressive] = useState(false)'), true)
  assert.equal(startSource.includes('const [isProgressiveVisible, setIsProgressiveVisible] = useState(false)'), true)
  assert.equal(startSource.includes('const shouldShowProgressive = isWebUrlReady || shouldRenderProgressive'), true)
  assert.equal(startSource.includes('const isProgressiveOpen = isWebUrlReady && isProgressiveVisible'), true)
  assert.equal(startSource.includes('setShouldRenderProgressive(true)'), true)
  assert.equal(startSource.includes('setIsProgressiveVisible(false)'), true)
  assert.equal(startSource.includes('window.requestAnimationFrame'), true)
  assert.equal(startSource.includes('frameId = window.requestAnimationFrame(() => {\n        setShouldRenderProgressive(true)\n        setIsProgressiveVisible(true)\n      })'), true)
  assert.equal(startSource.includes('frameId = window.requestAnimationFrame(() => setIsProgressiveVisible(false))'), true)
  assert.equal(startSource.includes('setShouldRenderProgressive(false), 420'), true)
  assert.equal(startSource.includes('setShouldRenderProgressive(false), 900'), false)
  assert.equal(startSource.includes('setTimeout(() => setIsProgressiveVisible'), false)
  assert.equal(startSource.includes('shouldShowProgressive ? ('), true)
  assert.equal(startSource.includes("className={`start-progressive ${isProgressiveOpen ? 'is-visible' : 'is-closing'}`}"), true)
  assert.equal(startSource.includes('start-progressive-inner'), true)
  assert.equal(startSource.includes('start-step start-step-note'), false)
  assert.equal(startSource.includes('start-step start-step-figma-copy'), true)
  assert.equal(startSource.includes('start-step start-step-figma-input'), true)
  assert.equal(startSource.includes('start-step start-step-options'), true)
  assert.equal(startSource.includes('start-step start-step-submit'), true)
  assert.equal(startSource.includes('aria-hidden={!isProgressiveOpen}'), true)
  assert.equal(startSource.includes('disabled={!isWebUrlReady || isScanning}'), true)
  assert.equal(startSource.includes('if (!canStartScan || isScanning) return'), true)
  assert.equal(startSource.includes('<TechScanOptions'), true)
  assert.equal(startSource.includes('onStartScan()'), true)
  assert.equal(startSource.includes('disabled={!canStartScan || isScanning}'), true)
  assert.equal(startSource.includes('start-submit-arrow'), false)
  assert.equal((startSource.match(/type="submit"/g) || []).length, 1)
  assert.equal(startSource.indexOf('start-step-figma-copy') < startSource.indexOf('start-step-figma-input'), true)
  assert.equal(startSource.indexOf('start-step-figma-input') < startSource.indexOf('start-step-options'), true)
  assert.equal(startSource.indexOf('start-step-options') < startSource.indexOf('primary-button start-submit start-step start-step-submit'), true)
  assert.equal(inputSource.includes('start-screen'), false)
  assert.equal(optionSource.includes('TECH_SCAN_OPTION_GROUPS'), true)
  assert.equal(optionSource.includes('tech-scan-options-summary-copy'), true)
  assert.equal(optionSource.includes('옵션 변경'), false)
  assert.equal(optionSource.includes('추가 Tech QA 선택 옵션 없음'), true)
  assert.equal(optionSource.includes('${selectedCount}개 Tech QA 선택 옵션 적용 중'), true)
  assert.equal(optionSource.includes('tech-scan-options-link'), true)
  assert.equal(optionSource.includes('tech-scan-options-chevron'), true)
  assert.equal(optionSource.includes('Tech QA 옵션 선택하기'), false)
  assert.equal(optionSource.includes('필요한 검사 항목을 선택하세요'), true)
  assert.equal(optionSource.includes('주요 검사'), true)
  assert.equal(optionSource.includes('모두 선택'), true)
  assert.equal(optionSource.includes('>선택 검사</span>'), false)
  assert.equal(optionSource.includes('>닫기<'), false)
  assert.equal(optionSource.includes('>취소<'), false)
  assert.equal(optionSource.includes('aria-label="닫기"'), true)
  assert.equal(optionSource.includes('title="닫기"'), true)
  assert.equal(optionSource.includes('<span aria-hidden="true">×</span>'), true)
  assert.equal(optionSource.includes('onClick={closeTechOptions}'), true)
  assert.equal(optionSource.includes('className="tech-scan-options-cancel-button"'), false)
  assert.equal(optionSource.includes('className="tech-scan-options-apply-button"'), true)
  assert.equal(optionSource.includes('onClick={applyTechOptions}'), true)
  assert.equal(optionSource.includes('항상 실행됨'), false)
  assert.equal(optionSource.includes('aria-label="선택 검사 모두 선택"'), true)
  assert.equal(optionSource.includes('indeterminate'), false)
  assert.equal(optionSource.includes('role="dialog"'), true)
  assert.equal(optionSource.includes('aria-modal="true"'), true)

  const startScreenCss = css.slice(css.indexOf('.start-screen {'), css.indexOf('.start-header'))
  const startBrandCss = css.slice(css.indexOf('.start-brand {'), css.indexOf('.start-brand strong'))
  const startInputCss = css.slice(css.indexOf('.start-input {'), css.indexOf('.start-input:hover:not(:disabled)'))
  const startInputValidCss = css.slice(css.indexOf('.start-input.is-valid,'), css.indexOf('.start-input.is-valid:focus,'))
  const figmaInputCss = css.slice(css.indexOf('.start-figma-composer .start-input {'), css.indexOf('.start-screen .tech-scan-options'))
  const startSubmitCss = css.slice(css.indexOf('.start-submit.primary-button {'), css.indexOf('.start-submit.primary-button:hover:not(:disabled)'))
  const startSubmitHoverCss = css.slice(css.indexOf('.start-submit.primary-button:hover:not(:disabled) {'), css.indexOf('.start-submit.primary-button:active:not(:disabled)'))
  const startSubmitActiveCss = css.slice(css.indexOf('.start-submit.primary-button:active:not(:disabled) {'), css.indexOf('.start-submit.primary-button:focus-visible'))
  const startSubmitFocusCss = css.slice(css.indexOf('.start-submit.primary-button:focus-visible {'), css.indexOf('.start-submit.primary-button:disabled'))
  const dialogFooterCss = css.slice(css.indexOf('.tech-scan-options-dialog-footer {'), css.indexOf('.tech-scan-options-dialog-header h2'))
  const closeButtonCss = css.slice(css.indexOf('.tech-scan-options-close-button {'), css.indexOf('.tech-scan-options-close-button:hover'))
  const applyButtonStart = css.lastIndexOf('.tech-scan-options-apply-button {', css.indexOf('.tech-scan-options-apply-button:hover:not(:disabled) {'))
  const applyButtonCss = css.slice(applyButtonStart, css.indexOf('.tech-scan-options-apply-button:hover:not(:disabled)'))
  const applyButtonHoverCss = css.slice(css.indexOf('.tech-scan-options-apply-button:hover:not(:disabled) {'), css.indexOf('.tech-scan-options-apply-button:active:not(:disabled)'))
  const applyButtonActiveCss = css.slice(css.indexOf('.tech-scan-options-apply-button:active:not(:disabled) {'), css.indexOf('.tech-scan-options-apply-button:focus-visible'))
  const checkboxCss = css.slice(css.indexOf('.tech-scan-option-row input,'), css.indexOf('.tech-scan-options-sheet-handle'))
  const checkedCheckboxCss = css.slice(css.indexOf('.tech-scan-option-row input:checked,'), css.indexOf('.tech-scan-option-row input:checked::before,'))
  const checkmarkCss = css.slice(css.indexOf('.tech-scan-option-row input::before,'), css.indexOf('.tech-scan-option-row input:hover:not(:disabled),'))

  assert.equal(css.includes('.start-screen'), true)
  assert.equal(css.includes('.start-header'), true)
  assert.equal(css.includes('.start-main'), true)
  assert.equal(css.includes('.start-hero'), true)
  assert.equal(css.includes('.start-history-button'), true)
  assert.equal(css.includes('.start-valid-check'), true)
  assert.equal(css.includes('.start-brand-symbol'), false)
  assert.equal(startBrandCss.includes('color: var(--start-mint-active);'), true)
  assert.equal(css.includes('width: min(100%, var(--start-content-width));'), true)
  assert.equal(css.includes('--start-bg: #f7faf9;'), true)
  assert.equal(css.includes('--start-mint: #43c4ad;'), true)
  assert.equal(css.includes('--start-mint-hover: #39b79f;'), true)
  assert.equal(css.includes('--start-mint-active: #2fa891;'), true)
  assert.equal(css.includes('--start-mint-soft: rgba(70, 201, 177, 0.14);'), true)
  assert.equal(css.includes('--start-input-height: 56px;'), true)
  assert.equal(css.includes('--start-input-radius: 16px;'), true)
  assert.equal(css.includes('--start-input-padding-inline: 20px;'), true)
  assert.equal(css.includes('--start-success: #238c69;'), true)
  assert.equal(css.includes('--start-success-border: rgba(35, 140, 105, 0.74);'), true)
  assert.equal(css.includes('--start-border: rgba(113, 133, 143, 0.3);'), true)
  assert.equal(css.includes('background-color: var(--start-bg);'), true)
  assert.equal((startScreenCss.match(/radial-gradient\(/g) || []).length, 3)
  assert.equal(css.includes('radial-gradient(ellipse 118% 58% at 50% 100%'), true)
  assert.equal(css.includes('rgba(75, 210, 188, 0.3)'), true)
  assert.equal(css.includes('rgba(100, 214, 194, 0.13)'), true)
  assert.equal(css.includes('rgba(190, 218, 226, 0.1)'), true)
  assert.equal(css.includes('.start-screen::before'), false)
  assert.equal(css.includes('.start-screen::after'), false)
  assert.equal(css.includes(`body {
  background`), false)
  assert.equal(startInputCss.includes('height: var(--start-input-height);'), true)
  assert.equal(startInputCss.includes('padding: 0 var(--start-input-padding-inline);'), true)
  assert.equal(startInputCss.includes('border: 1.5px solid var(--start-border);'), true)
  assert.equal(startInputCss.includes('border-radius: var(--start-input-radius);'), true)
  assert.equal(startInputCss.includes('font-size: 16px;'), true)
  assert.equal(startInputCss.includes('line-height: 1.2;'), true)
  assert.equal(startInputCss.includes('var(--start-mint)'), false)
  assert.equal(startInputCss.includes('var(--start-success'), false)
  assert.equal(css.includes('border-color: var(--start-focus-border);'), true)
  assert.equal(css.includes('box-shadow: 0 0 0 3px var(--start-mint-soft)'), true)
  assert.equal(figmaInputCss.includes('height:'), false)
  assert.equal(figmaInputCss.includes('border-radius:'), false)
  assert.equal(startInputValidCss.includes('border-width: 1.5px;'), true)
  assert.equal(startInputValidCss.includes('border-color: var(--start-success-border);'), true)
  assert.equal(css.includes('.start-progressive'), true)
  assert.equal(css.includes('grid-template-rows: 0fr;'), true)
  assert.equal(css.includes('grid-template-rows: 1fr;'), true)
  assert.equal(css.includes('.start-progressive-inner'), true)
  assert.equal(css.includes('min-height: 0;'), true)
  assert.equal(css.includes('transform: translateY(16px);'), true)
  assert.equal(css.includes('filter: blur(4px);'), true)
  assert.equal(css.includes('transform: translateY(8px);'), true)
  assert.equal(css.includes('filter: blur(2px);'), true)
  assert.equal(css.includes('.start-progressive.is-closing'), true)
  assert.equal(css.includes('cubic-bezier(0.16, 1, 0.3, 1)'), true)
  assert.equal(css.includes('animation-delay: 0ms;'), true)
  assert.equal(css.includes('transition-delay: 0ms;'), true)
  assert.equal(css.includes('transition-delay: 80ms;'), true)
  assert.equal(css.includes('transition-delay: 160ms;'), true)
  assert.equal(css.includes('transition-delay: 240ms;'), true)
  assert.equal(css.includes('transition-delay: 360ms;'), false)
  assert.equal(css.includes('1000ms cubic-bezier(0.16, 1, 0.3, 1)'), true)
  assert.equal(css.includes('900ms cubic-bezier(0.16, 1, 0.3, 1)'), true)
  assert.equal(css.includes('420ms cubic-bezier(0.16, 1, 0.3, 1)'), true)
  assert.equal(css.includes('@media (prefers-reduced-motion: reduce)'), true)
  assert.equal(css.includes('.start-submit'), true)
  assert.equal(css.includes('height: 56px;'), true)
  assert.equal(css.includes('grid-template-rows: minmax(clamp(36px, 8vh, 86px), 0.7fr) auto minmax(clamp(64px, 14vh, 154px), 1fr);'), true)
  assert.equal(css.includes('padding: 0 24px clamp(48px, 8vh, 92px);'), true)
  assert.equal(css.includes('grid-row: 2;'), true)
  assert.equal(css.includes('grid-template-rows: auto 1fr;'), true)
  assert.equal(css.includes('border: 0;'), true)
  assert.equal(css.includes('min-height: 100dvh;'), true)
  assert.equal(css.includes('repeating-linear-gradient'), false)
  assert.equal(css.includes('font-family: Pretendard, Inter, "Segoe UI", "Apple SD Gothic Neo", "Noto Sans KR", sans-serif;'), true)
  assert.equal(css.includes('.start-copy h1'), true)
  assert.equal(css.includes('.start-copy p'), true)
  assert.equal(css.includes('font-size: 15px;'), true)
  assert.equal(css.includes('font-weight: 430;'), true)
  assert.equal(css.includes('text-align: center;'), true)
  assert.equal(css.includes('.start-field'), true)
  assert.equal(css.includes('.start-composer'), true)
  assert.equal(css.includes('.start-input-mark'), false)
  assert.equal(css.includes('.start-field.is-valid .start-input'), true)
  assert.equal(css.includes('.start-field.is-invalid .start-input'), true)
  assert.equal(css.includes('.start-sr-only'), true)
  assert.equal(css.includes('.start-submit-arrow'), false)
  assert.equal(css.includes('.start-submit.primary-button::before'), false)
  assert.equal(css.includes('.start-submit.primary-button::after'), false)
  assert.equal(startSubmitCss.includes('height: 56px;'), true)
  assert.equal(startSubmitCss.includes('border-radius: 16px;'), true)
  assert.equal(startSubmitCss.includes('border: 1px solid rgba(43, 169, 142, 0.72);'), true)
  assert.equal(getDeclarationValue(startSubmitCss, 'color'), '#ffffff')
  assert.equal(isMintFill(getDeclarationValue(startSubmitCss, 'background')), true)
  assert.equal(getDeclarationValue(startSubmitCss, 'background').includes('255, 255, 255'), false)
  assert.equal(startSubmitCss.includes('#3b82f6'), false)
  assert.equal(startSubmitCss.includes('#1f5fd1'), false)
  assert.equal(startSubmitCss.includes('#182235'), false)
  assert.equal((startSubmitCss.match(/box-shadow:/g) || []).length, 1)
  assert.equal(startSubmitCss.includes('box-shadow: 0 10px 24px rgba(42, 161, 141, 0.18);'), true)
  assert.equal(getDeclarationValue(startSubmitHoverCss, 'color'), '#ffffff')
  assert.equal(isMintFill(getDeclarationValue(startSubmitHoverCss, 'background')), true)
  assert.equal(startSubmitHoverCss.includes('border-color: rgba(43, 169, 142, 0.86);'), true)
  assert.equal(startSubmitHoverCss.includes('transform: translateY(-1px);'), true)
  assert.equal((startSubmitHoverCss.match(/box-shadow:/g) || []).length, 1)
  assert.equal(getDeclarationValue(startSubmitActiveCss, 'color'), '#ffffff')
  assert.equal(isMintFill(getDeclarationValue(startSubmitActiveCss, 'background')), true)
  assert.equal(startSubmitActiveCss.includes('transform: translateY(0);'), true)
  assert.equal((startSubmitActiveCss.match(/box-shadow:/g) || []).length, 1)
  assert.equal(startSubmitFocusCss.includes('outline: 3px solid rgba(70, 201, 177, 0.28);'), true)
  assert.equal(css.includes('.tech-scan-options-cancel-button'), false)
  assert.equal(dialogFooterCss.includes('justify-content: flex-end;'), true)
  assert.equal(closeButtonCss.includes('width: 34px;'), true)
  assert.equal(closeButtonCss.includes('height: 34px;'), true)
  assert.equal(closeButtonCss.includes('background: transparent;'), true)
  assert.equal(getDeclarationValue(applyButtonCss, 'color'), '#ffffff')
  assert.equal(isMintFill(getDeclarationValue(applyButtonCss, 'background')), true)
  assert.equal(applyButtonCss.includes('border: 1px solid var(--start-mint, #43c4ad);'), true)
  assert.equal(applyButtonCss.includes('box-shadow: 0 8px 18px rgba(42, 161, 141, 0.18);'), true)
  assert.equal(getDeclarationValue(applyButtonHoverCss, 'color'), '#ffffff')
  assert.equal(isMintFill(getDeclarationValue(applyButtonHoverCss, 'background')), true)
  assert.equal(applyButtonHoverCss.includes('transform: translateY(-1px);'), true)
  assert.equal(getDeclarationValue(applyButtonActiveCss, 'color'), '#ffffff')
  assert.equal(isMintFill(getDeclarationValue(applyButtonActiveCss, 'background')), true)
  assert.equal(applyButtonActiveCss.includes('transform: translateY(0);'), true)
  assert.equal(checkboxCss.includes('appearance: none;'), true)
  assert.equal(checkboxCss.includes('border: 1.5px solid rgba(113, 133, 143, 0.55);'), true)
  assert.equal(isMintFill(getDeclarationValue(checkedCheckboxCss, 'background')), true)
  assert.equal(checkedCheckboxCss.includes('border-color: var(--start-mint, #43c4ad);'), true)
  assert.equal(checkmarkCss.includes('border: solid #ffffff;'), true)
  assert.notEqual(getDeclarationValue(checkedCheckboxCss, 'background'), '#ffffff')
  assert.notEqual(getDeclarationValue(checkedCheckboxCss, 'background'), '#fff')
  assert.equal(checkboxCss.includes('outline: 2px solid rgba(70, 201, 177, 0.32);'), true)
  assert.equal(css.includes('.start-screen .tech-scan-options-summary-copy'), true)
  assert.equal(css.includes('text-decoration: underline;'), true)
  assert.equal(css.includes('.tech-scan-options-status'), true)
  assert.equal(css.includes('.tech-scan-options-action'), false)
  assert.equal(css.includes('.tech-scan-options-secondary-row'), true)
  assert.equal(css.includes('.tech-scan-options-link'), true)
  assert.equal(css.includes('.tech-scan-options-chevron'), true)
  assert.equal(css.includes('--start-option-muted: #718087;'), true)
  assert.equal(css.includes('--start-option-success: var(--start-success);'), true)
  assert.equal(css.includes(`.tech-scan-options-primary {
  color: var(--start-option-muted);
  font-weight: 520;
}`), true)
  assert.equal(css.includes(`.tech-scan-options-secondary-row {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  color: var(--start-option-muted);
  font-size: 13px;
  font-weight: 520;
  line-height: 1.25;
  opacity: 1;
}`), true)
  assert.equal(css.includes(`.tech-scan-options-link {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  color: var(--start-option-muted);
  font-size: 13px;
  font-weight: 520;
  line-height: 1.25;`), true)
  assert.equal(css.includes(`.tech-scan-options-status-check {
  display: inline-flex;
  align-items: center;
  color: var(--start-option-success);
  font-size: 13px;
  font-weight: 760;
  line-height: 1.25;
  opacity: 1;
}`), true)
  assert.equal(css.includes('.start-screen .tech-scan-options-trigger:hover:not(:disabled) .tech-scan-options-link'), true)
  assert.equal(css.includes('transform: translateX(2px) rotate(45deg);'), true)
  assert.equal(css.includes('border: 0;'), true)
  assert.equal(css.includes('background: transparent;'), true)
  assert.equal(css.includes('box-shadow: none;'), true)
  assert.equal(css.includes(`.start-screen .tech-scan-options-trigger {
  display: inline-flex;
  width: auto;`), true)
  assert.equal(css.includes('.qa-start-'), false)
  assert.equal(css.includes('.result-topbar .workspace-tabs'), true)
  assert.equal(css.includes('justify-content: center;'), true)
})

test('app renders sidebar-free scanning and result shells with centered tabs only after scan starts', () => {
  const appSource = readSource('src/App.jsx')
  const emptySource = readSource('src/components/EmptyState.jsx')
  const css = readSource('src/App.css')
  const scanningCss = css.slice(css.indexOf('/* Modern AI loading screen.'), css.indexOf('@media (prefers-reduced-motion: reduce)'))

  assert.equal(appSource.includes('if (isScanning) {'), true)
  assert.equal(appSource.includes('<main className="scanning-screen" aria-live="polite">'), true)
  assert.equal(appSource.includes('{scanningContent}'), true)
  assert.equal(appSource.indexOf('if (isScanning) {') < appSource.indexOf('<div className="result-shell">'), true)
  assert.equal(appSource.includes('<div className="result-shell">'), true)
  assert.equal(appSource.includes('<header className="result-topbar">'), true)
  assert.equal(appSource.includes('<main className="result-content" aria-live="polite">'), true)
  assert.equal(appSource.includes('<WorkspaceTabs'), true)
  assert.equal(appSource.includes('disabledTabs={{ visual: !isVisualTabEnabled, tech: !isTechTabEnabled }}'), true)
  assert.equal(appSource.includes('<TechQaPanel result={techResult} />'), true)
  assert.equal(appSource.includes('<VisualQaPanel'), true)
  assert.equal(appSource.includes('<HistoryPanel'), true)
  assert.equal(appSource.includes('<InputPanel'), false)
  assert.equal(appSource.includes('isSidebarCollapsed'), false)
  assert.equal(appSource.includes('onToggleCollapsed'), false)

  assert.equal(css.includes('.scanning-screen'), true)
  assert.equal(css.includes('place-items: center;'), true)
  assert.equal(css.includes('.scanning-screen > .empty-state'), true)
  assert.equal(scanningCss.includes('background-image:'), true)
  assert.equal(scanningCss.includes('rgba(75, 210, 188, 0.3)'), true)
  assert.equal(scanningCss.includes('.scanning-screen > .empty-state > div'), true)
  assert.equal(scanningCss.includes('border: 0;'), true)
  assert.equal(scanningCss.includes('background: transparent;'), true)
  assert.equal(scanningCss.includes('box-shadow: none;'), true)
  assert.equal(scanningCss.includes('.scanning-screen .state-indicator,'), true)
  assert.equal(scanningCss.includes('.scanning-screen .empty-state.is-scanning > div::after'), true)
  assert.equal(scanningCss.includes('display: none;'), true)
  assert.equal(scanningCss.includes('.scanning-screen .state-label'), true)
  assert.equal(scanningCss.includes('clip-path: inset(50%);'), true)
  assert.equal(emptySource.includes('const scanStages = isScanning ? getStages({ isTech, combined }) : []'), true)
  assert.equal(emptySource.includes('const activeStageIndex = isScanning ? getActiveStageIndex({ isTech, combined, scanStage }) : 0'), true)
  assert.equal(emptySource.includes('const stageRollOffset = Math.max(activeStageIndex - 1, 0)'), true)
  assert.equal(emptySource.includes('className="scan-stage-viewport"'), true)
  assert.equal(emptySource.includes("style={{ '--active-stage-index': activeStageIndex, '--stage-roll-offset': stageRollOffset }}"), true)
  assert.equal(emptySource.includes('scanStages.map((stage, index) => ('), true)
  assert.equal(emptySource.includes('getStageClassName(index, activeStageIndex)'), true)
  assert.equal(emptySource.includes('className="scan-stage-current-sr"'), true)
  assert.equal(emptySource.includes('aria-hidden="true"'), true)
  assert.equal(scanningCss.includes('.scanning-screen .scan-stage-viewport'), true)
  assert.equal(scanningCss.includes('width: min(100%, 680px);'), true)
  assert.equal(scanningCss.includes('height: 252px;'), true)
  assert.equal(scanningCss.includes('padding: 10px 18px;'), true)
  assert.equal(scanningCss.includes('overflow: hidden;'), true)
  assert.equal(scanningCss.includes('mask-image: linear-gradient'), true)
  assert.equal(scanningCss.includes('display: flex;'), true)
  assert.equal(scanningCss.includes('flex-direction: column;'), true)
  assert.equal(scanningCss.includes('transform: translateY(calc(var(--stage-roll-offset, 0) * -1 * var(--scan-stage-step)));'), true)
  assert.equal(scanningCss.includes('transition: transform 760ms cubic-bezier(0.22, 1, 0.36, 1);'), true)
  assert.equal(scanningCss.includes('position: absolute;\n  inset: 0;'), false)
  assert.equal(scanningCss.includes('opacity: 0;'), false)
  assert.equal(scanningCss.includes('opacity: 1;'), true)
  assert.equal(scanningCss.includes('opacity: 0.48;'), true)
  assert.equal(scanningCss.includes('opacity: 0.62;'), true)
  assert.equal(scanningCss.includes('font-size: clamp(30px, 2.5vw, 42px);'), true)
  assert.equal(scanningCss.includes('max-width: 980px;'), true)
  assert.equal(scanningCss.includes('white-space: nowrap;'), true)
  assert.equal(scanningCss.includes("content: '✓';"), true)
  assert.equal(scanningCss.includes('border-color: var(--scan-mint);'), true)
  assert.equal(scanningCss.includes('background: var(--scan-mint);'), true)
  assert.equal(scanningCss.includes('animation: scanCurrentPulse 1800ms ease-in-out infinite;'), true)
  assert.equal(scanningCss.includes('#1c69d4'), false)
  assert.equal(scanningCss.includes('#2b7cf2'), false)
  assert.equal(css.includes('@media (prefers-reduced-motion: reduce)'), true)
  assert.equal(css.includes(`.scanning-screen .scan-stage-list,
  .scanning-screen .empty-state .scan-stage-list.scan-stage-list {
    transition: none;`), true)
  assert.equal(css.includes('.result-shell'), true)
  assert.equal(css.includes('.result-topbar'), true)
  assert.equal(css.includes('.result-content'), true)
  assert.equal(css.includes('width: min(100%, 1600px);'), true)
})

test('app default scan flow calls integrated qa endpoint only', () => {
  const source = readSource('src/App.jsx')
  assert.equal(source.includes("fetch('/api/qa/run'"), true)
  assert.equal(source.includes("fetch('/api/ai-review/from-payload'"), true)
  assert.equal(source.includes('body: JSON.stringify({ webUrl, figmaUrl, scanOptions })'), true)
  assert.equal(source.includes('basic:'), false)
  assert.equal(source.includes('main:'), false)
  assert.equal(source.includes('requestQaRun(webUrl, frameUrl, techScanOptions)'), true)
  assert.equal(source.includes('const [techScanOptions, setTechScanOptions] = useState(() => createDefaultTechScanOptions())'), true)
  assert.equal(source.includes('techScanOptions={techScanOptions}'), true)
  assert.equal(source.includes('onTechScanOptionsChange={setTechScanOptions}'), true)
  assert.equal(source.includes("fetch('/api/scan'"), false)
  assert.equal(source.includes("fetch('/api/visual/payload'"), false)
  assert.equal(source.includes('pageTitle={techResult?.pageTitle}'), true)
})

test('tech qa panel hides unselected result sections from normalized scan options only', () => {
  const source = readSource('src/components/TechQaPanel.jsx')
  const visualSource = readSource('src/components/VisualQaPanel.jsx')

  assert.equal(source.includes('const scanOptions = view.scanOptions'), true)
  assert.equal(source.includes('{scanOptions.url ? ('), true)
  assert.equal(source.includes('{scanOptions.click ? ('), true)
  assert.equal(source.includes('{scanOptions.landing ? <LandingPageSection'), true)
  assert.equal(source.includes('{scanOptions.form ? ('), true)
  assert.equal(source.includes('{scanOptions.hover ? ('), true)
  assert.equal(source.includes('{scanOptions.modal ? ('), true)
  assert.equal(source.includes('{scanOptions.scroll ? ('), true)
  assert.equal(source.includes('{scanOptions.responsive ? ('), true)
  assert.equal(source.includes('{scanOptions.download ? ('), true)
  assert.equal(source.includes('{scanOptions.cookie ? ('), true)
  assert.equal(source.includes('{scanOptions.image ? ('), true)
  assert.equal(source.includes('{scanOptions.performance ? ('), true)
  assert.equal(source.includes('{scanOptions.seo ? ('), true)
  assert.equal(source.includes('{scanOptions.markup ? <MarkupAccessibilitySection items={markupItems} /> : null}'), true)
  assert.equal(source.includes('<DeveloperInfo view={view} result={result} scanOptions={scanOptions} />'), true)
  assert.equal(source.includes('<RawDetails view={view} result={result} scanOptions={scanOptions} />'), true)
  assert.equal(visualSource.includes('scanOptions'), false)
})

test('app keeps result tabs neutral before scan and disables unavailable scopes', () => {
  const appSource = readSource('src/App.jsx')
  const tabSource = readSource('src/components/WorkspaceTabs.jsx')
  const emptySource = readSource('src/components/EmptyState.jsx')
  assert.equal(appSource.includes("useState('overview')"), true)
  assert.equal(appSource.includes('mode="overview"'), true)
  assert.equal(appSource.includes('disabledTabs={{ visual: !isVisualTabEnabled, tech: !isTechTabEnabled }}'), true)
  assert.equal(appSource.includes("setActiveTab(frameUrl ? 'visual' : 'tech')"), true)
  assert.equal(tabSource.includes('disabled={Boolean(disabledTabs[tab.id])}'), true)
  assert.equal(emptySource.includes("if (isOverview) return 'PagePilot QA'"), true)
  assert.equal(emptySource.includes('Web URL만 입력하면 Tech QA를 실행합니다.'), true)
  assert.equal(emptySource.includes('Figma URL을 함께 입력하면 Visual QA도 같이 실행합니다.'), true)
})

test('history panel supports new scan and item deletion without navigation reload', () => {
  const appSource = readSource('src/App.jsx')
  const historySource = readSource('src/components/HistoryPanel.jsx')
  assert.equal(historySource.includes('새 검사'), true)
  assert.equal(historySource.includes('검사 기록'), true)
  assert.equal(historySource.includes('저장된 QA 결과를 다시 확인할 수 있습니다.'), true)
  assert.equal(historySource.includes('history-toolbar'), true)
  assert.equal(historySource.includes('disabled={isScanning}'), true)
  assert.equal(historySource.includes("event.stopPropagation()"), true)
  assert.equal(historySource.includes('이 검사 기록을 삭제할까요?'), true)
  assert.equal(historySource.includes('aria-label="검사 기록 삭제"'), true)
  assert.equal(historySource.includes('history-delete-button'), true)
  assert.equal(appSource.includes("setActiveTab('overview')"), true)
  assert.equal(appSource.includes('setSelectedHistoryId(item.id)'), true)
  assert.equal(appSource.includes('deleteHistoryItem(id)'), true)
  assert.equal(appSource.includes('window.location'), false)
  assert.equal(appSource.includes('location.reload'), false)
})

test('tech qa detail triggers stay in row summaries across table types and history restore', () => {
  const source = readSource('src/components/TechQaPanel.jsx')
  const css = readSource('src/App.css')
  const appSource = readSource('src/App.jsx')

  assert.equal(source.includes('tech-table-row tech-row-details tech-row-with-details'), true)
  assert.equal(source.includes('tech-link-row tech-row-details tech-row-with-details'), true)
  assert.equal(source.includes('tech-click-issue-row tech-click-row tech-row-details tech-row-with-details'), true)
  assert.equal(source.includes('className="tech-detail-trigger">상세'), false)
  assert.equal(source.includes('className="tech-detail-toggle" aria-hidden="true"'), true)
  assert.equal(source.includes('<span className="tech-detail-chevron">▸</span>'), true)
  assert.equal(source.includes("aria-label={isOpen ? '상세 닫기' : '상세 열기'}"), true)
  assert.equal(source.includes('aria-expanded={isOpen}'), true)
  assert.equal((source.match(/<DetailChevron \/>/g) || []).length, 1)
  assert.equal(source.includes('tech-row-summary'), true)
  assert.equal(source.includes('<div className="tech-row-detail-body">'), true)
  assert.equal(source.includes('<summary>상세</summary>'), false)
  assert.equal(css.includes('.tech-table-row > .tech-row-summary'), true)
  assert.equal(css.includes('.tech-link-row > .tech-link-row-summary'), true)
  assert.equal(css.includes('.tech-click-row > .tech-click-row-summary'), true)
  assert.equal(css.includes('.tech-markup-row > .tech-row-summary'), true)
  assert.equal(css.includes('--tech-link-columns: 88px minmax(160px, 0.8fr) minmax(0, 2fr) 72px 100px 40px;'), true)
  assert.equal(css.includes('--tech-click-columns: 88px minmax(150px, 0.9fr) minmax(104px, 0.6fr) minmax(0, 1.7fr) 100px 40px;'), true)
  assert.equal(css.includes('--tech-markup-columns: minmax(180px, 1.3fr) 92px minmax(110px, 0.8fr) minmax(110px, 0.7fr) 40px;'), true)
  assert.equal(css.includes('grid-template-columns: var(--tech-link-columns);'), true)
  assert.equal(css.includes('grid-template-columns: var(--tech-click-columns);'), true)
  assert.equal(css.includes('grid-template-columns: var(--tech-markup-columns);'), true)
  assert.equal(css.includes('.tech-row-summary > * {\n  min-width: 0;'), true)
  assert.equal(css.includes('.tech-link-row.tech-row-with-details,\n.tech-click-issue-row.tech-row-with-details,\n.tech-click-row.tech-row-with-details,\n.tech-markup-row.tech-row-with-details'), true)
  assert.equal(css.includes('.tech-more-details > .tech-more-summary'), true)
  assert.equal(css.includes('.tech-link-more-table'), true)
  assert.equal(css.includes('.tech-link-table-body'), true)
  assert.equal(css.includes('.tech-link-more-table .tech-link-row'), true)
  assert.equal(css.includes('.tech-click-more-details'), true)
  assert.equal(css.includes('.tech-click-more-table'), true)
  assert.equal(css.includes('.tech-click-table-body'), true)
  assert.equal(css.includes('.tech-click-more .tech-click-row-summary'), true)
  assert.equal(css.includes('display: block;\n  width: 100%;\n  min-width: 0;'), true)
  assert.equal(css.includes('.tech-row-detail-body {\n  grid-column: 1 / -1;'), true)
  assert.equal(css.includes('width: 100%;\n  min-width: 0;\n  max-width: 100%;'), true)
  assert.equal(css.includes('overflow-wrap: anywhere;'), true)
  assert.equal(css.includes('word-break: break-word;'), true)
  assert.equal(css.includes('.tech-row-detail-body .tech-row-details:not(.tech-row-with-details)'), true)
  assert.equal(css.includes('overflow-x: auto;'), true)
  assert.equal(css.includes('.tech-detail-toggle'), true)
  assert.equal(css.includes('.tech-row-with-details[open] .tech-detail-chevron'), true)
  assert.equal(css.includes('transform: rotate(90deg);'), true)
  assert.equal(css.includes('.tech-row-with-details > summary::-webkit-details-marker'), true)
  assert.equal(css.includes('.tech-row-with-details > summary::marker'), true)
  assert.equal(appSource.includes('setTechResult(item.tech?.compactResult || null)'), true)
  assert.equal(appSource.includes('setTechResult(item.result)'), true)
  assert.equal(appSource.includes('<TechQaPanel result={techResult} />'), true)
})

test('result headers share report labels and omit copy buttons', () => {
  const appSource = readSource('src/App.jsx')
  const visualSource = readSource('src/components/VisualQaPanel.jsx')
  const techSource = readSource('src/components/TechQaPanel.jsx')
  const auditSource = readSource('src/components/AuditHeader.jsx')
  const css = readSource('src/App.css')
  const productionJsx = [appSource, visualSource, techSource, auditSource].join('\n')

  assert.equal(visualSource.includes('Visual QA Report · {formatDate(meta.createdAt)}'), true)
  assert.equal(visualSource.includes('createVisualQaTitle({ pageTitle, result })'), true)
  assert.equal(techSource.includes('Tech QA Report · {formatScanTime(result.scannedAt)}'), true)
  assert.equal(techSource.includes('createTechQaTitle(view.title)'), true)
  assert.equal(appSource.includes('setVisualResult(item.visual?.compactResult || null)'), true)
  assert.equal(appSource.includes('setTechResult(item.tech?.compactResult || null)'), true)
  assert.equal(appSource.includes('<VisualQaPanel'), true)
  assert.equal(appSource.includes('<TechQaPanel result={techResult} />'), true)
  assert.equal(appSource.includes('copyStatus='), false)
  assert.equal(appSource.includes('onCopyResult'), false)
  assert.equal(appSource.includes('onCopyReport'), false)
  assert.equal(appSource.includes('visualCopyStatus'), false)
  assert.equal(appSource.includes('techCopyStatus'), false)
  assert.equal(productionJsx.includes('결과 복사'), false)
  assert.equal(css.includes('.audit-header-top > div {\n  flex: 1;\n  min-width: 0;'), true)
})

test('tech qa screen removes the priority summary card and keeps lower detail sections', () => {
  const source = readSource('src/components/TechQaPanel.jsx')
  const css = readSource('src/App.css')
  const completionIndex = source.indexOf('<TechCompletionCard completion={display.completion} />')
  const basicIndex = source.indexOf('title="주요 검사 결과"')

  assert.equal(source.includes("const MARKUP_ACCESSIBILITY_PRIMARY_IDS = ['meta', 'image-alt', 'external-links']"), true)
  assert.equal(source.includes("const MARKUP_ACCESSIBILITY_DETAIL_IDS = ['meta', 'image-alt', 'external-links', 'headings', 'duplicate-ids', 'forms', 'unlabeled-clickables']"), true)
  assert.equal(source.includes('id="tech-links-section"'), true)
  assert.equal(source.includes('function LinkTableHead()'), true)
  assert.equal((source.match(/<LinkTableHead \/>/g) || []).length, 2)
  assert.equal(source.includes('summaryClassName="tech-link-row-summary"'), true)
  assert.equal(source.includes('tech-more-details tech-normal-links-more tech-link-more'), true)
  assert.equal(source.includes('className="tech-more-summary"'), true)
  assert.equal(source.includes('tech-link-table tech-link-more-table'), true)
  assert.equal(source.includes('tech-link-table-body'), true)
  assert.equal(source.includes('tech-link-table is-collapsed'), false)
  assert.equal(source.includes('tech-detail-list tech-link-more'), false)
  assert.equal(source.includes('id="tech-click-section"'), true)
  assert.equal(source.includes('id="tech-click-actual-errors"'), false)
  assert.equal(source.includes('id="tech-click-warnings"'), false)
  assert.equal(source.includes('id="tech-landing-section"'), true)
  assert.equal(source.includes('id="tech-markup-accessibility-section"'), true)
  assert.equal(source.includes('tech-markup-head'), true)
  assert.equal(source.includes('tech-markup-row tech-markup-check-row'), true)
  assert.equal(source.includes('마크업 및 접근성 검사'), true)
  assert.equal(source.includes('getPriorityDetailTargetId'), false)
  assert.equal(source.includes("if (item.type === 'link') return 'tech-links-section'"), false)
  assert.equal(source.includes('if (item.detailTargetId) return item.detailTargetId'), false)
  assert.equal(source.includes("String(item.id || '').startsWith('click-actions')"), false)
  assert.equal(source.includes("if (item.id === 'landing-pages') return 'tech-landing-section'"), false)
  assert.equal(source.includes('MARKUP_ACCESSIBILITY_DETAIL_IDS.includes(item.id)'), true)
  assert.equal(source.includes('id={item.rowId || getBasicCheckDetailId(item)}'), true)
  assert.equal(source.includes('id={item.rowId}'), true)
  assert.equal(source.includes('tech-detail-jump'), false)
  assert.equal(source.includes('아래 상세 보기'), false)
  assert.equal(source.includes('우선 확인 결과 ${display.priorityRows.length}건'), false)
  assert.equal(source.includes('오류 ${display.priorityCounts.error}건 · 확인 필요 ${display.priorityCounts.warn}건'), false)
  assert.equal(source.includes('display.priorityVisibility.visibleItems'), false)
  assert.equal(source.includes('<PriorityTableRow item={item}'), false)
  assert.equal(source.includes('Tech QA 검사가 완료되었습니다. 아래 항목에서 오류 및 확인 필요 결과를 확인해 주세요.'), true)
  assert.equal(completionIndex > -1 && basicIndex > completionIndex, true)
  assert.equal(source.includes('detail={<IssueDetails item={item} />}'), true)
  assert.equal(source.includes('ResourceSizeDetails'), true)
  assert.equal(source.includes('LargeResourceList'), true)
  assert.equal(css.includes('#tech-landing-section'), true)
  assert.equal(css.includes('#tech-markup-accessibility-section'), true)
  assert.equal(css.includes('.tech-markup-check-list'), true)
  assert.equal(css.includes('.tech-detail-jump'), false)
})

test('tech qa click action section uses compact tables and collapsed non-issue groups', () => {
  const source = readSource('src/components/TechQaPanel.jsx')
  const css = readSource('src/App.css')

  assert.equal(source.includes('function ClickActionSummary'), false)
  assert.equal(source.includes('tech-click-summary'), false)
  assert.equal(source.includes('MetricPill'), false)
  assert.equal(source.includes('ClickActionTable'), true)
  assert.equal(source.includes('CollapsedClickRows'), true)
  assert.equal(source.includes('const visibility = getSectionVisibility(rows, { maxVisible: 5'), true)
  assert.equal(source.includes('getCollapsedResultsLabel(visibility.hiddenItems.length)'), true)
  assert.equal(source.includes("statusOrder: ['error', 'warn', 'info', 'ok']"), true)
  assert.equal(source.includes('id={item.rowId}'), true)
  assert.equal(source.includes("item.actionClassification === 'safe-click-skipped'"), true)
  assert.equal(source.includes('LandingPageSection'), true)
  assert.equal(source.includes('LandingPageTableHead'), true)
  assert.equal(source.includes('검사할 URL 이동 또는 새 창 결과가 없습니다.'), true)
  assert.equal(source.includes('getCollapsedResultsLabel(visibleGroups.hiddenCount)'), true)
  assert.equal(source.includes('const visibleGroups = getVisibleLinkGroups(rows)'), true)
  assert.equal(source.includes("isOpen ? '접기' : label"), true)
  assert.equal(source.includes('function getTechRowKey(item = {}, prefix = \'row\', index = 0)'), true)
  assert.equal(source.includes("key={item.rowKey || getTechRowKey(item, 'link-hidden', index)}"), true)
  assert.equal(source.includes("key={item.rowKey || getTechRowKey(item, 'landing-hidden', index)}"), true)
  assert.equal(source.includes("key={item.rowKey || getTechRowKey(item, 'click', index)}"), true)
  assert.equal(css.includes('.tech-compact-card {\n  display: grid;\n  gap: 12px;'), true)
  assert.equal(css.includes('#tech-click-actual-errors'), false)
  assert.equal(css.includes('#tech-click-warnings'), false)
  assert.equal(css.includes('.tech-click-summary'), false)
  assert.equal(css.includes('.tech-metric-pill'), false)
  assert.equal(css.includes('.tech-click-more'), true)
})

test('tech qa includes new Form Hover Modal sections without restoring priority summary', () => {
  const source = readSource('src/components/TechQaPanel.jsx')
  const utilSource = readSource('src/utils/techQa.js')
  const panelViewSource = readSource('src/utils/techQaPanelView.js')
  const landingIndex = source.indexOf('<LandingPageSection groups={view.landingPageGroups} rows={display.detailRows.landingRows} />')
  const formIndex = source.indexOf('title="Form QA"')
  const hoverIndex = source.indexOf('title="Hover / Dropdown QA"')
  const modalIndex = source.indexOf('title="Modal QA"')
  const markupIndex = source.indexOf('<MarkupAccessibilitySection items={markupItems} />')

  assert.equal(source.includes('title="Form QA"'), true)
  assert.equal(source.includes('title="Hover / Dropdown QA"'), true)
  assert.equal(source.includes('title="Modal QA"'), true)
  assert.equal(source.includes('검사할 입력 폼이 없습니다.'), true)
  assert.equal(source.includes('검사할 Hover 또는 드롭다운 요소가 없습니다.'), true)
  assert.equal(source.includes('검사할 모달 트리거가 없습니다.'), true)
  assert.equal(source.includes('우선 확인 결과'), false)
  assert.equal(utilSource.includes("'form-interaction'"), true)
  assert.equal(utilSource.includes("'hover-interaction'"), true)
  assert.equal(utilSource.includes("'modal-interaction'"), true)
  assert.equal(panelViewSource.includes('formRows'), true)
  assert.equal(panelViewSource.includes('hoverRows'), true)
  assert.equal(panelViewSource.includes('modalRows'), true)
  assert.equal(landingIndex > -1 && formIndex > landingIndex && hoverIndex > formIndex && modalIndex > hoverIndex && markupIndex > modalIndex, true)
})

test('empty state uses different scanning stages for tech-only and integrated runs', () => {
  const source = readSource('src/components/EmptyState.jsx')
  const css = readSource('src/App.css')
  assert.equal(source.includes('Web 페이지 정보를 수집하고 있습니다.'), true)
  assert.equal(source.includes('페이지 구조와 주요 기능을 검사하고 있습니다.'), true)
  assert.equal(source.includes('선택한 Tech QA 항목을 분석하고 있습니다.'), true)
  assert.equal(source.includes('Web 페이지를 수집하고 있습니다.'), false)
  assert.equal(source.includes('접속, 링크, 이미지 및 메타 정보를 검사하고 있습니다.'), false)
  assert.equal(source.includes('모바일과 기술 품질 항목을 확인하고 있습니다.'), false)
  assert.equal(source.includes('Web 페이지와 검사 데이터를 수집하고 있습니다.'), true)
  assert.equal(source.includes('시안 정보와 Web 데이터를 비교하고 있습니다.'), true)
  assert.equal(source.includes('AI가 확인된 차이를 최종 검토하고 있습니다.'), true)
  assert.equal((source.match(/'Web 페이지 정보를 수집하고 있습니다\.'|'페이지 구조와 주요 기능을 검사하고 있습니다\.'|'선택한 Tech QA 항목을 분석하고 있습니다\.'|'최종 QA 결과를 정리하고 있습니다\.'/g) || []).length >= 4, true)
  assert.equal(css.includes('grid-template-columns: 18px minmax(0, 1fr);'), true)
  assert.equal(source.includes('scan-stage-row'), true)
  assert.equal(source.includes('scan-stage-dot'), true)
  assert.equal(source.includes('scan-stage-text'), true)
  assert.equal(css.includes('white-space: nowrap;'), true)
  assert.equal(css.includes('.scan-stage-list li::before {\n  display: none;'), true)
})

test('visual accordions share closed row height and hide collapsed bodies', () => {
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(css.includes('.visual-detail-accordion > summary,'), true)
  assert.equal(css.includes('.full-findings-accordion > summary,'), true)
  assert.equal(css.includes('.developer-info-accordion > summary'), true)
  assert.equal(css.includes('min-height: 58px;'), true)
  assert.equal(css.includes('.developer-info-accordion:not([open]) > .developer-info-body'), true)
  assert.equal(css.includes('display: none;'), true)
})

test('visual panel keeps AI review report UI out of the default view', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  assert.equal(source.includes('배포 판단'), false)
  assert.equal(source.includes('AI 종합 검토'), false)
  assert.equal(source.includes('ReleaseDecisionCard'), false)
  assert.equal(source.includes('KeyIssueList'), false)
  assert.equal(source.includes('MetricPill'), false)
  assert.equal(source.includes('createVisualDifferenceReport(result, aiReview)'), false)
  assert.equal(source.includes('createVisualDisplayIssues(result, aiReview)'), true)
  assert.equal(source.includes('rawVisionCount=${differenceMeta.rawVisionCount}'), true)
  assert.equal(source.includes('createVisualQaTitle({ pageTitle, result })'), true)
  assert.equal(source.includes('AI 시각 비교'), false)
  assert.equal(source.includes('AI 분석 요약'), true)
  assert.equal(source.includes('visualDifferences'), false)
  assert.equal(source.includes('회신 초안 보기'), false)
  assert.equal(source.includes('clientReplyDraft'), false)
})

test('visual panel hides severity badges in default difference cards', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(source.includes('formatSeverity'), false)
  assert.equal(source.includes('difference-severity'), false)
  assert.equal(source.includes('Critical'), false)
  assert.equal(source.includes('Warning'), false)
  assert.equal(source.includes('Check'), false)
  assert.equal(css.includes('.difference-severity'), false)
  assert.equal(source.includes('item.severity'), false)
  assert.equal(source.includes('figmaValue'), true)
  assert.equal(source.includes('webValue'), true)
})

test('visual panel removes inaccurate image position highlighting', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(source.includes('scrollTo('), false)
  assert.equal(source.includes('highlightRatio'), false)
  assert.equal(source.includes('setHighlight'), false)
  assert.equal(source.includes('image-highlight-band'), false)
  assert.equal(source.includes('createRatioScrollSynchronizer'), false)
  assert.equal(css.includes('image-highlight-band'), false)
})

test('visual panel uses restored stable image comparison shell', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  assert.equal(source.includes('visual-comparison-viewport'), true)
  assert.equal(source.includes('visual-comparison-columns'), true)
  assert.equal(source.includes('onScroll='), false)
  assert.equal(css.includes('.visual-comparison-viewport'), true)
  assert.equal(css.includes('.visual-comparison-columns'), true)
  assert.equal(fs.existsSync('src/utils/visualScrollSync.js'), false)
})

test('empty state separates pre-scan guidance from scanning progress', () => {
  const source = fs.readFileSync('src/components/EmptyState.jsx', 'utf8')
  assert.equal(source.includes("return isTech ? 'Tech QA' : 'Visual QA'"), true)
  assert.equal(source.includes('Web URL과 Figma URL을 입력하세요. Figma 시안과 Web 페이지를 비교합니다.'), true)
  assert.equal(source.includes('Web URL을 입력하고 검사를 시작하세요. 페이지 접속 상태와 기술 항목을 검사합니다.'), true)
  assert.equal(source.includes('Playwright:'), false)
  assert.equal(source.includes('Figma API:'), false)
  assert.equal(source.includes('Canonical:'), false)
  assert.equal(source.includes('멀티모달 AI:'), false)
  assert.equal(source.includes('결과 생성:'), false)
  assert.equal(source.includes('1차 수집'), false)
  assert.equal(source.includes('Web 페이지 정보를 수집하고 있습니다.'), true)
  assert.equal(source.includes('페이지 구조와 주요 기능을 검사하고 있습니다.'), true)
  assert.equal(source.includes('선택한 Tech QA 항목을 분석하고 있습니다.'), true)
  assert.equal(source.includes('Web 페이지를 수집하고 있습니다.'), false)
  assert.equal(source.includes('2차 비교'), false)
  assert.equal(source.includes('시안 정보와 Web 데이터를 비교하고 있습니다.'), true)
  assert.equal(source.includes('3차 검증'), false)
  assert.equal(source.includes('구조와 콘텐츠의 차이를 검증하고 있습니다.'), true)
  assert.equal(source.includes("title: '최종 검토'"), false)
  assert.equal(source.includes('AI가 확인된 차이를 최종 검토하고 있습니다.'), true)
  assert.equal(source.includes("title: '결과 정리'"), false)
  assert.equal(source.includes('최종 QA 결과를 정리하고 있습니다.'), true)
  assert.equal(source.includes('<strong>{stage.title}</strong>'), false)
  assert.equal(source.includes('<span>{stage.description}</span>'), false)
  assert.equal(source.includes('AI Vision'), false)
})

test('visual panel renders simplified default sections and folded detail analysis', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const imageIndex = source.indexOf('Figma / Web 이미지 비교')
  const differenceIndex = source.indexOf('핵심 차이')
  const fullIndex = source.indexOf('전체 발견 항목 보기')
  const detailIndex = source.indexOf('<details className="detail-card visual-detail-accordion">')
  assert.equal(source.includes('visual-severity-grid'), false)
  assert.equal(source.includes('<details className="detail-card visual-card-list-card" open>'), false)
  assert.equal(source.includes('<section className="visual-detail-panel"'), false)
  assert.equal(source.includes('상세 분석 보기'), true)
  assert.equal(source.includes('멀티모달 AI 검증 완료'), true)
  assert.equal(source.includes('Playwright 수집 완료'), true)
  assert.equal(source.includes('Figma API 비교 완료'), true)
  assert.equal(source.includes('데이터 정규화 완료'), true)
  assert.equal(source.includes('멀티모달 AI 최종 검토 완료'), true)
  assert.equal(source.includes('<details className="detail-card visual-detail-accordion" open>'), false)
  assert.equal(imageIndex > -1, true)
  assert.equal(differenceIndex > imageIndex, true)
  assert.equal(fullIndex > differenceIndex, true)
  assert.equal(detailIndex > fullIndex, true)
  assert.equal(source.includes('규칙 기반 Critical / Warning / Check'), false)
  assert.equal(source.includes('규칙 기반 검사 상세'), false)
  assert.equal(source.includes('RuleIssueList'), false)
  assert.equal(source.includes('visual-detail-stack'), true)
  assert.equal(source.includes('visual-sub-accordion'), true)
  assert.equal(source.includes('<DetailAccordion title="Hero"'), true)
  assert.equal(source.includes('<DetailAccordion title="CTA"'), true)
  assert.equal(source.includes('<DetailAccordion title="Price / Numeric"'), true)
  assert.equal(source.includes('<DetailAccordion title="Media"'), true)
  assert.equal(source.includes('<DetailAccordion title="Text"'), true)
  assert.equal(source.includes('<DetailAccordion title="System"'), true)
  assert.equal(source.includes('<details className="visual-sub-accordion" open>'), false)
  assert.equal(source.includes('review?.summary'), false)
  assert.equal(source.includes('Payload Version'), true)
  assert.equal(source.includes('Raw Vision Count'), true)
  assert.equal(source.includes('Final Report Items'), true)
  assert.equal(source.includes('Comparison Differences'), true)
  assert.equal(source.includes('AI Visual Differences'), true)
  assert.equal(source.includes('CTA Evidence'), true)
  assert.equal(source.includes('Media Evidence'), true)
  assert.equal(source.includes('Price/Numeric Evidence'), true)
  assert.equal(source.includes('Display Candidates'), true)
  assert.equal(source.includes('Display Groups'), true)
  assert.equal(source.includes('Grouped Issue Count'), true)
  assert.equal(source.includes('Exact Duplicate Removed'), true)
  assert.equal(source.includes('Core Issue Count'), true)
  assert.equal(source.includes('Excluded From Core'), true)
  assert.equal(source.includes('Engine Data Deleted'), true)
  assert.equal(source.includes('displayCount'), false)
  assert.equal(source.includes('UI 표시 개수'), true)
  assert.equal(source.includes('나머지 {remainingCount}건 더보기'), false)
  assert.equal(source.includes('items.slice'), false)
  assert.equal(source.includes('remainingCount'), false)
  assert.equal(source.includes('getDifferenceCategoryClass'), true)
  assert.equal(source.includes('difference-category-chip'), true)
  assert.equal(source.includes('is-text'), true)
  assert.equal(source.includes('is-cta'), true)
  assert.equal(source.includes('is-media'), true)
  assert.equal(source.includes('is-price'), true)
  assert.equal(source.includes('is-missing'), true)
  assert.equal(source.includes('AI Vision'), false)
  assert.equal(source.includes('<span>{item.description}</span>'), false)
})

test('visual panel completed AI meta only shows model and duration by default', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const completeStart = source.indexOf('function AiMultimodalComplete')
  const completeEnd = source.indexOf('function AiVisionSummary')
  const completeSource = source.slice(completeStart, completeEnd)
  assert.equal(completeSource.includes('label="모델"'), true)
  assert.equal(completeSource.includes('label="처리 시간"'), true)
  assert.equal(completeSource.includes('label="이미지"'), false)
  assert.equal(completeSource.includes('label="Fallback"'), false)
  assert.equal(completeSource.includes('label="최종 차이"'), false)
  assert.equal(source.includes('<AiMultimodalComplete aiReview={aiReview} />'), true)
})

test('visual panel renders the integrated display issue source without default list limits', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  assert.equal(source.includes('const displayIssues = createVisualDisplayIssues(result, aiReview)'), true)
  assert.equal(source.includes('const coreIssues = createCoreVisualIssues(displayIssues)'), true)
  assert.equal(source.includes('const coreIssueGroups = createVisualIssueGroups(coreIssues, { mergeReadableAreas: true })'), true)
  assert.equal(source.includes('const fullIssueGroups = createVisualIssueGroups(displayIssues)'), true)
  assert.equal(source.includes('<IssueGroupList groups={coreIssueGroups} />'), true)
  assert.equal(source.includes('<IssueGroupList groups={fullIssueGroups} compact />'), true)
  assert.equal(source.includes('formatGroupIssueCount(fullIssueGroups.length'), true)
  assert.equal(source.includes('formatIssueCountSummary(coreGroupMeta.groupedIssueCount ?? coreIssues.length)'), true)
  assert.equal(source.includes('displayIssues.slice'), false)
  assert.equal(source.includes('issueGroups.slice'), false)
  assert.equal(source.includes('displayCount'), false)
})

test('visual panel renders grouped issue cards without hiding the issue list in details', () => {
  const source = fs.readFileSync('src/components/VisualQaPanel.jsx', 'utf8')
  const css = fs.readFileSync('src/App.css', 'utf8')
  const groupedIndex = source.indexOf('<IssueGroupList groups={coreIssueGroups} />')
  const fullIndex = source.indexOf('<IssueGroupList groups={fullIssueGroups} compact />')
  const detailIndex = source.indexOf('<details className="detail-card visual-detail-accordion">')
  assert.equal(source.includes('핵심 차이'), true)
  assert.equal(source.includes('전체 발견 항목 보기'), true)
  assert.equal(source.includes('issue-group-list'), true)
  assert.equal(source.includes('issue-group-card'), true)
  assert.equal(source.includes('issue-group-items'), true)
  assert.equal(source.includes('issue-group-values'), true)
  assert.equal(groupedIndex > -1 && fullIndex > groupedIndex && detailIndex > fullIndex, true)
  assert.equal(css.includes('.issue-group-list'), true)
  assert.equal(css.includes('.issue-group-card'), true)
  assert.equal(css.includes('.issue-group-item::before'), true)
  assert.equal(css.includes('.issue-group-item.is-text .difference-category-chip'), true)
  assert.equal(css.includes('.issue-group-values'), true)
})
